Improvement in bumpversion option
HPInc/ml-git pull request #102
Opened 2021-04-23 17:42 UTC by lucasncabral

In the add command the user has an option (--bumpversion) that allows to increase the version of the entity. This increment is accomplished by adding one to the value of the version the user is in.

In some scenarios, this increment of one causes an error, since a tag with that specific version already exists - the user checked out tag 1 and tags 2 and 3 already exist, the --bumpversion would take the spec to point to version 2, but there is already a version 2.

This improvement makes the option able to identify the last version and define the version in the spec as the last plus one. In the scenario described above, bumpversion would make the spec point to version 4.

2021-04-23 18:43 UTC, Mun1z approved these changes

2021-05-06 18:57 UTC, gilMars approved these changes

2021-05-19 15:13 UTC, andersonpablosilva approved these changes

2021-05-19 16:10 UTC, gpretto requested changes
Few changes.

2021-05-19 16:10 UTC, gpretto commented on ml_git/spec.py
> +def incr_version(file, target_version, repo_type=DATASETS):
We use "incr_version" in many places? I will suggest to change this method to inc_version or "increment_version"...

2021-05-19 16:10 UTC, gpretto commented on tests/unit/test_metadata.py
> +        clear(self.test_dir)
```suggestion
        spec_path = 'dataset-ex'
        config['mlgit_path'] = self.test_dir
        m = Metadata('', '', config, DATASETS)
        m.init()

        tag_list = ['computer__images__dataset-ex__1', 'computer__images__dataset-ex__2']
        with mock.patch('ml_git.metadata.Metadata.list_tags', return_value=tag_list):
            last_version = m.get_last_tag_version(spec_path)
        self.assertEqual(last_version, 2)

        tag_list = []
        with mock.patch('ml_git.metadata.Metadata.list_tags', return_value=tag_list):
            last_version = m.get_last_tag_version(spec_path)
        self.assertEqual(last_version, 0)
        clear(self.test_dir)
```

2021-05-19 17:27 UTC, lucasncabral commented on ml_git/metadata.py
> +    def _get_target_tag(tags, target_version):
The function was moved to be declared before being used at 2d26696.

2021-05-19 17:28 UTC, lucasncabral commented on ml_git/spec.py
> +def incr_version(file, target_version, repo_type=DATASETS):
As we only use it in one place it was possible to rename it easily. Method was renamed to `increment_version` at 2d26696.

2021-05-19 17:29 UTC, lucasncabral commented on tests/unit/test_metadata.py
> +        clear(self.test_dir)
The variable was renamed at 2d26696.

2021-05-21 13:40 UTC, gpretto approved these changes

2021-05-21 15:59 UTC, diego-pedroso approved these changes

2021-05-24 11:11 UTC, merged