Adding commands to support config versioning
HPInc/ml-git pull request #113
Opened 2021-06-04 13:17 UTC by lucasncabral

This PR has the development of two commands that aim to allow the user to be able to version the configuration file through ml-git. The commands are:

**ml-git repository config push:**
```
Usage: ml-git repository config push [OPTIONS]

  Create a new version of the ml-git configuration file. This command
  internally runs git's add, commit and push commands.

Options:
  -m, --message TEXT  Use the provided <msg> as the commit message.
  --verbose           Debug mode
  --help              Show this message and exit.
```

**ml-git repository remote config add:**
```
Usage: ml-git repository remote config add [OPTIONS] REMOTE_URL

  Starts a git at the root of the project and configure the remote.

Options:
  --verbose  Debug mode
```

**Also**, the `ml-git repository config` command has been changed to `ml-git repository config show`. And the behavior of `ml-git clone` was reversed - At the time of clone, the tracking of the repository is kept, and if the user doesn't want to, he can use the `--untracked` option.

2021-06-04 14:13 UTC, gilMars commented on ml_git/_metadata.py
> +    def init_local_repo(self):
I think that the else statement isn't necessary.

2021-06-04 14:13 UTC, gilMars commented on ml_git/utils.py
> +    if os.path.exists(gitignore_path):
Why not only overwrite the file content?

2021-06-04 14:23 UTC, lucasncabral commented on ml_git/utils.py
> +    if os.path.exists(gitignore_path):
In the case where the user has this repository just for the configuration file, I believe it would not be a problem to overwrite. But imagine a scenario where he has files referring to the project, and he is versioning together with the configuration file. Something like:
```
project/
├── .ml-git
│    ├── dataset
└──  └── config
├── dataset
│   └── folderA
│       └── folderB
│           └── dataset-ex
├── one_file.py
├── another_file.py
└── ...
```

The `.ml-git/config` file may be being versioned into the same repository as the `one_file.py` and `another_file.py` files.  Therefore, the user may already have a `.gitignore` and we don't want to delete its settings, just add the necessary ones for ml-git.

2021-06-04 15:16 UTC, lucasncabral commented on ml_git/_metadata.py
> +    def init_local_repo(self):
The unnecessary line has been removed in 410ddf6.

2021-06-04 18:18 UTC, Mun1z approved these changes

2021-06-04 18:45 UTC, gilMars commented on ml_git/utils.py
> +    if os.path.exists(gitignore_path):
I agree with you.

2021-06-04 18:46 UTC, gilMars approved these changes

2021-06-04 20:29 UTC, andersonpablosilva commented on docs/mlgit_internals.md
> +<summary> <code>ml-git repository config show </code></summary>
This commands are reversed, right?

2021-06-04 20:32 UTC, lucasncabral commented on docs/mlgit_internals.md
> +<summary> <code>ml-git repository config show </code></summary>
Right. The commands descriptions have been adjusted in 041c196.

2021-06-04 20:33 UTC, andersonpablosilva approved these changes

2021-06-07 13:35 UTC, gpretto requested changes

2021-06-07 13:35 UTC, gpretto commented on docs/mlgit_commands.md
> +  Create a new version of the ml-git configuration file. This command
```suggestion
  Create a new version of the ML-Git configuration file. This command
```

2021-06-07 13:35 UTC, gpretto commented on docs/mlgit_internals.md
> +This processing includes executing the git add, git commit, and git push commands. After execution the user will be able to observe the update of the configuration file in the Git repository.
```suggestion
This processing includes executing the git add, git commit, and git push commands. After execution, the user will be able to observe the update of the configuration file in the Git repository.
```

2021-06-07 17:02 UTC, lucasncabral commented on docs/mlgit_commands.md
> +  Create a new version of the ml-git configuration file. This command
The suggestion was applied in 40b444f.

2021-06-07 17:02 UTC, lucasncabral commented on docs/mlgit_internals.md
> +This processing includes executing the git add, git commit, and git push commands. After execution the user will be able to observe the update of the configuration file in the Git repository.
The suggestion was applied in 40b444f.

2021-06-15 12:11 UTC, gpretto approved these changes

2021-06-15 16:38 UTC, diego-pedroso approved these changes

2021-06-15 17:33 UTC, merged