Adding method in API to list all versions of an entity
HPInc/ml-git pull request #114
Opened 2021-06-10 11:15 UTC by lucasncabral

**Depends on #111.**

Adding method in ML-Git API, which aims to list all versions of a specific entity. This method uses the Github API.

```
def get_entity_versions(self, entity_name, metadata_repo_name):
    """Get a list of spec versions found for an especific entity.

    Args:
        entity_name (str): The name of the entity you want to get the versions.
        metadata_repo_name (str): The repository name where the metadata is located in GitHub.

    Returns:
        list of class SpecVersion.
    """
```

**Usage example:** 
```
from ml_git import api
github_token = ''
api_url = 'https://api.github.com'
manager = api.init_entity_manager(github_token, api_url)

versions = manager.get_entity_versions('dataset-ex', metadata_repo_name='user/metadata_repository')
```

The variable `versions` should look something like:
```
[{
  "tag": "test__dataset-ex__2",
  "version": 2,
  "mutability": "mutable",
  "categories": [
    "test"
  ],
  "storage_type": "s3h",
  "bucket": "mlgit-bucket",
  "amount": 2,
  "size": "7.2 kB"
}, {
  "tag": "test__dataset-ex__1",
  "version": 1,
  "mutability": "mutable",
  "categories": [
    "test"
  ],
  "storage_type": "s3h",
  "bucket": "mlgit-bucket",
  "amount": 1,
  "size": "3.6 kB"
}]
```

2021-06-10 11:42 UTC, Mun1z approved these changes

2021-06-17 17:59 UTC, gilMars commented on docs/api/README.md
> +            metadata_repo_name (str): The repository name where the metadata is located in GitHub.
The repository name of config,yaml or a repository of versioned entitiy?

2021-06-18 13:42 UTC, lucasncabral commented on docs/api/README.md
> +            metadata_repo_name (str): The repository name where the metadata is located in GitHub.
The message has been updated to make it clearer which repository.
Also, some variables have been renamed, so that the user can understand when to use the configuration repository (`config_repo_name`) and when to use the metadata repository (`metadata_repo_name`).

These changes were applied at d364d49.

2021-06-18 13:47 UTC, gilMars approved these changes

2021-06-23 21:42 UTC, andersonpablosilva requested changes

2021-06-23 21:42 UTC, andersonpablosilva commented on ml_git/relationship/models/entity.py
> +        self.metadata_owner_name = repository.owner.name
Move metadata attributes to a Metadata class.

2021-06-23 21:42 UTC, andersonpablosilva commented on ml_git/relationship/models/entity.py
> +        self.metadata_owner_name = repository.owner.name
Also, update all classes to the final version: see PR #118.

2021-06-23 21:42 UTC, andersonpablosilva commented on ml_git/relationship/models/spec_version.py
> +        name (str): The name of the entity.
Same as before, review the attributes.

2021-06-28 18:42 UTC, lucasncabral commented on docs/api/README.md
>          metadata_owner_email (str): The email of the repository owner.
The changes that had been applied in #115, related to the metadata and storage models, were brought to this branch.

2021-06-28 18:42 UTC, lucasncabral commented on ml_git/relationship/models/entity.py
> +        self.metadata_owner_name = repository.owner.name
Same comment as before.

2021-06-28 18:42 UTC, lucasncabral commented on ml_git/relationship/models/spec_version.py
> +        name (str): The name of the entity.
Done at 5f8df7a.

2021-07-01 04:12 UTC, andersonpablosilva approved these changes

2021-07-02 15:16 UTC, andersonpablosilva requested changes

2021-07-02 15:16 UTC, andersonpablosilva commented on docs/api/README.md
>      """Class that's represents a ml-entity.
```suggestion
    """Class that represents an ml-entity.
```

2021-07-02 15:16 UTC, andersonpablosilva commented on docs/api/README.md
> +    """Class that's represents a ml-entity spec version.
```suggestion
    """Class that represents an ml-entity spec version.
```

2021-07-02 15:16 UTC, andersonpablosilva commented on docs/api/README.md
> +    """Class that's represents an ml-entity metadata.
```suggestion
    """Class that represents an ml-entity metadata.
```

2021-07-02 15:16 UTC, andersonpablosilva commented on docs/api/README.md
> +    """Class that's represents an ml-entity storage.
```suggestion
    """Class that represents an ml-entity storage.
```

2021-07-02 15:16 UTC, andersonpablosilva commented on ml_git/relationship/models/entity.py
>      """Class that's represents an ml-entity.
```suggestion
    """Class that represents an ml-entity.
```

2021-07-02 15:16 UTC, andersonpablosilva commented on ml_git/relationship/models/metadata.py
> +    """Class that's represents an ml-entity metadata.
```suggestion
    """Class that represents an ml-entity metadata.
```

2021-07-02 15:16 UTC, andersonpablosilva commented on ml_git/relationship/models/spec_version.py
> +    """Class that's represents an ml-entity spec version.
```suggestion
    """Class that represents an ml-entity spec version.
```

2021-07-02 15:16 UTC, andersonpablosilva commented on ml_git/relationship/models/storage.py
> +    """Class that's represents an ml-entity storage.
```suggestion
    """Class that represents an ml-entity storage.
```

2021-07-02 15:23 UTC, lucasncabral commented on docs/api/README.md
>      """Class that's represents a ml-entity.
Text has been updated in c8ce0bd.

2021-07-02 15:23 UTC, lucasncabral commented on docs/api/README.md
> +    """Class that's represents a ml-entity spec version.
Text has been updated in c8ce0bd.

2021-07-02 15:23 UTC, lucasncabral commented on docs/api/README.md
> +    """Class that's represents an ml-entity storage.
Text has been updated in c8ce0bd.

2021-07-02 15:23 UTC, lucasncabral commented on ml_git/relationship/models/entity.py
>      """Class that's represents an ml-entity.
Text has been updated in c8ce0bd.

2021-07-02 15:23 UTC, lucasncabral commented on ml_git/relationship/models/metadata.py
> +    """Class that's represents an ml-entity metadata.
Text has been updated in c8ce0bd.

2021-07-02 15:23 UTC, lucasncabral commented on ml_git/relationship/models/spec_version.py
> +    """Class that's represents an ml-entity spec version.
Text has been updated in c8ce0bd.

2021-07-02 15:23 UTC, lucasncabral commented on ml_git/relationship/models/storage.py
> +    """Class that's represents an ml-entity storage.
Text has been updated in c8ce0bd.

2021-07-02 15:24 UTC, lucasncabral commented on docs/api/README.md
> +    """Class that's represents an ml-entity metadata.
Text has been updated in c8ce0bd.

2021-07-02 15:24 UTC, andersonpablosilva approved these changes

2021-07-05 11:01 UTC, gpretto requested changes
A few changes.

2021-07-05 11:01 UTC, gpretto commented on ml_git/relationship/models/spec_version.py
> +        amount (str): The amount of the version files.
```suggestion
        amount (str): The amount of the versioned files.
```
I was thinking about we use `total_files`, `versioned_files`, or `total_versioned_files`... I believe amount is to generic...

2021-07-06 11:21 UTC, lucasncabral commented on docs/api/README.md
> +        amount (str): The amount of the version files.
The suggestion was applied in 06ec778.

2021-07-06 11:21 UTC, lucasncabral commented on ml_git/relationship/models/entity.py
> +        last_spec_version (SpecVersion): The spec file of entity last version.
The suggestion was applied in 06ec778.

2021-07-06 11:22 UTC, gpretto approved these changes
Good job!

2021-07-06 11:22 UTC, lucasncabral commented on ml_git/relationship/models/spec_version.py
> +        amount (str): The amount of the version files.
I agree. The attribute was renamed to `total_versioned_files`. 
This change was made in 06ec778.

2021-07-07 19:18 UTC, merged