Feature/api get linked entities version
HPInc/ml-git pull request #115
Opened 2021-06-11 12:00 UTC by Mun1z

**Depends on #114.**

Adding method in ML-Git API, which aims to list all linked entities of a specific entity versions. This method uses the Github API.

```
def get_linked_entities(self, entity_name, entity_version, metadata_repo_name):
    """Get a list of linked entities found for an entity version.

    Args:
        entity_name (str): The name of the entity you want to get the linked entities.
        entity_version (str): The version of the entity you want to get the linked entities.
        metadata_repo_name (str): The repository name where the metadata is located in GitHub.

    Returns:
        list of LinkedEntity.
    """
```

**Usage example:** 
```
from ml_git import api
github_token = ''
api_url = 'https://api.github.com'
manager = api.init_entity_manager(github_token, api_url)

linked_entities = manager.get_linked_entities('entity_name', 'entity_version', metadata_repo_name='user/metadata_repository')
```

The variable `linked_entities ` should look something like:
```
[{
  "tag": "test__datasets-ex__1",
  "name": "datasets-ex",
  "version": "1",
  "entity_type": "dataset"
}, {
  "tag": "test__labels-ex__1",
  "name": "labels-ex",
  "version": "1",
  "entity_type": "labels"
}]
```

2021-06-18 17:01 UTC, lucasncabral approved these changes

2021-06-18 19:07 UTC, Mun1z commented on ml_git/relationship/models/metadata.py
> +class Metadata:
In the entity's output it was defined that it should be "metadata".

2021-07-02 12:17 UTC, user-mlgit approved these changes

2021-07-02 12:19 UTC, gilMars approved these changes

2021-07-02 14:28 UTC, andersonpablosilva approved these changes

2021-07-02 15:34 UTC, lucasncabral commented on ml_git/relationship/models/linked_entity.py
> +    """Class that's represents an linked ml-entity.
Text has been updated in 0ad9e12.

2021-07-05 11:18 UTC, gpretto requested changes
Few changes.

2021-07-05 11:18 UTC, gpretto commented on docs/api/README.md
> +        tag (str): The tag of the ml-entity spec version.
Is it necessary use entity for the 'entity_type'? I would suggest have all attributes containing the name entity or neither.

2021-07-05 11:18 UTC, gpretto commented on ml_git/relationship/models/linked_entity.py
> +        tag (str): The tag of the ml-entity spec version.
Is it necessary use entity for the 'entity_type'? I would suggest have all attributes containing the name entity or neither.

2021-07-07 11:55 UTC, Mun1z commented on ml_git/relationship/models/linked_entity.py
> +        tag (str): The tag of the ml-entity spec version.
Done on commit: https://github.com/HPInc/ml-git/pull/115/commits/8e642e1fed659efb88308ccccd96a90178c24697

2021-07-07 11:55 UTC, Mun1z commented on docs/api/README.md
> +        tag (str): The tag of the ml-entity spec version.
Done on commit: https://github.com/HPInc/ml-git/pull/115/commits/8e642e1fed659efb88308ccccd96a90178c24697

2021-07-28 19:42 UTC, gpretto requested changes

2021-07-28 19:42 UTC, gpretto commented on docs/api/README.md
> +        entity_type (str): The type of the ml-entity (datasets, models, labels).
```suggestion
        type (str): The type of the ml-entity (datasets, models, labels).
```

I think we lost this change.

2021-07-28 19:42 UTC, gpretto commented on ml_git/relationship/entity_manager.py
> +            entity_version (str): The version of the entity you want to get the linked entities.
```suggestion
            name (str): The name of the entity you want to get the linked entities.
            version (str): The version of the entity you want to get the linked entities.
```
In other parts of this code we use the variable name without the entity. Unless it is not valid for this scenario, I think we can keep the same pattern.

2021-07-29 13:29 UTC, Mun1z commented on ml_git/relationship/entity_manager.py
> +            entity_version (str): The version of the entity you want to get the linked entities.
Yes, done on commit: https://github.com/HPInc/ml-git/pull/115/commits/d6f30e8e5d15e7e96d06733c9182e0872c051978

2021-07-29 13:29 UTC, Mun1z commented on docs/api/README.md
> +        entity_type (str): The type of the ml-entity (datasets, models, labels).
Nice, done on commit: https://github.com/HPInc/ml-git/pull/115/commits/d6f30e8e5d15e7e96d06733c9182e0872c051978

2021-07-29 18:11 UTC, gpretto approved these changes

2021-07-30 13:34 UTC, merged