Adding support for defining the .mlgitignore file
HPInc/ml-git pull request #125
Opened 2021-07-08 14:19 UTC by lucasncabral

Inside an entity's directory it is possible that the user has files that he does not want to version. With that in mind, this PR adds support for defining the `.mlgitignore` file which should define rules to indicate which files should be ignored.

The `.mlgitignore` file must be defined in the entity root folder - This means that each entity can have its `.mlgitignore` file, and the rules within the file must contain only file paths for that entity.

workspace structure example:
```
project/
├── datasets
│      └── dataset-ex
│          └── data
│              └── file.png
│              └── file.txt
│              └── file2.txt
│              └── augmented
│                  └── file.png
│          └── dataset-ex.spec
│          └── .mlgitignore <- HERE
├── .ml-git
│    ├── datasets
└──  └── config
```

The `.mlgitignore` rules follows the `.gitignore` rules standards. Example of `.mlgitignore` for the worksapce structure above:

```
# Ignore all PNG files inside data directory
data/*.png 

# Ignore specific file
data/file2.txt

# Ignore all JPG files in the entitiy
*.jpg

# Ignore all files inside a folder
data/augmented/
```

The rules defined inside `.mlgitignore`, besides determining which files should not be versioned, also cause these files not to be presented in the status command.

2021-07-13 04:13 UTC, andersonpablosilva requested changes

2021-07-13 04:13 UTC, andersonpablosilva commented on ml_git/file_system/index.py
> +            args = {'wp': self.wp, 'basepath': base_path, 'f_index_file': f_index_file, 'all_files': all_files, 'dirpath': dir_path}
Shouldn't we rename these keys too (`'basepath'`, `'dirpath'`)?

2021-07-13 04:13 UTC, andersonpablosilva commented on tests/unit/test_utils.py
> +        ignore_rules = ['data/*.png', 'ignored-folder/', '*.jpg', 'data/file-ignored.txt']
Maybe we can test more complex rules like `data/**/*.ext*`.

2021-07-13 11:51 UTC, lucasncabral commented on ml_git/file_system/index.py
> +    def _add_dir(self, dir_path, manifest_path, file_path='', ignore_rules=None):
The method has been moved to be defined before using it. This change was applied in 6a961f1.

2021-07-13 11:51 UTC, lucasncabral commented on ml_git/utils.py
> +        if fnmatch.fnmatch(file_path, ignore):
`ignore` has been replaced by `rule` in 6a961f1. Thanks for the suggestions.

2021-07-13 11:51 UTC, lucasncabral commented on ml_git/file_system/index.py
> +            args = {'wp': self.wp, 'basepath': base_path, 'f_index_file': f_index_file, 'all_files': all_files, 'dirpath': dir_path}
The keys have been renamed to follow the pattern in 6a961f1.

2021-07-13 11:55 UTC, lucasncabral commented on tests/unit/test_utils.py
> +        ignore_rules = ['data/*.png', 'ignored-folder/', '*.jpg', 'data/file-ignored.txt']
Added some new rules for testing: `'data/**/*.tx*'`, `'**/*.test*'`, `'**/access.[0-2].log'`, `'access.[a-c]*'`.

It is important to note that we are using the [fnmatch](https://docs.python.org/3/library/fnmatch.html) lib to perform this comparison between the rules and the file path. The lib is expected to have the proper tests to match the rules.

2021-07-13 13:11 UTC, andersonpablosilva approved these changes

2021-07-16 12:54 UTC, gilMars approved these changes

2021-07-16 14:05 UTC, Mun1z approved these changes

2021-07-28 19:48 UTC, gpretto approved these changes

2021-07-29 11:29 UTC, merged