Adding ML-Git Uninstall Section
HPInc/ml-git pull request #138
Opened 2021-08-30 17:21 UTC by gilMars

2021-08-30 17:38 UTC, Mun1z approved these changes

2021-08-31 11:38 UTC, lucasncabral reviewed
I think adding a section on how to uninstall may end up polluting this file, maybe it's the case to create another file and just add the link to it, even in the final section 'Links'. It's a suggestion.

2021-08-31 11:55 UTC, gilMars commented
> I think adding a section on how to uninstall may end up polluting this file, maybe it's the case to create another file and just add the link to it, even in the final section 'Links'. It's a suggestion.

Create uninstall section in another file is not intuitive, and uninstall process is aggregated with install process.

2021-08-31 12:10 UTC, lucasncabral approved these changes

2021-09-03 21:22 UTC, andersonpablosilva requested changes

2021-09-03 21:22 UTC, andersonpablosilva commented on README.md
> +
Please, remove this section. We've updated the installation process and can keep the documentation simple by just recommending uninstalling using pip.

2021-09-08 14:12 UTC, gilMars commented on README.md
> +
Removed in f957e701. Thanks a lot.

2021-09-08 14:20 UTC, andersonpablosilva approved these changes

2021-09-08 18:08 UTC, merged