Bugfix/graph error output
HPInc/ml-git pull request #143
Opened 2021-09-03 19:01 UTC by GustavoMaciel

ml-git repository graph with python error:
![image](https://user-images.githubusercontent.com/23001961/132044561-3a5fa9b8-d4a6-4779-992d-fbcf32d447aa.png)

after fix:
![image](https://user-images.githubusercontent.com/23001961/132053751-64bb6492-417e-42ed-99af-ab4fdceda97d.png)

Changed the command to end the function when no entity is found and also changed the message when a repository is not found for an entity in the LocalEntityManager class

2021-09-07 11:20 UTC, gilMars approved these changes

2021-09-07 11:55 UTC, lucasncabral approved these changes

2021-09-08 14:45 UTC, lucasncabral approved these changes

2021-09-08 17:40 UTC, andersonpablosilva requested changes

2021-09-08 17:40 UTC, andersonpablosilva commented on ml_git/ml_git_message.py
> +    'ERROR_REPOSITORY_NOT_FOUND_FOR_ENTITY': 'No repositories found for %s, verify your configurations!',
```suggestion
    'WARN_REPOSITORY_NOT_FOUND_FOR_ENTITY': 'No repositories found for %s, verify your configurations!',
```

Please, move this constant to the warning block below.

2021-09-08 18:10 UTC, GustavoMaciel commented on ml_git/ml_git_message.py
> +    'ERROR_REPOSITORY_NOT_FOUND_FOR_ENTITY': 'No repositories found for %s, verify your configurations!',
Changed in 4616d37

2021-09-08 18:11 UTC, andersonpablosilva approved these changes

2021-09-08 18:13 UTC, merged