Updating docs to use MinIO by default
HPInc/ml-git pull request #160
Opened 2021-09-15 13:02 UTC by GustavoMaciel

Updating in the docs all the usages of the command `$ ml-git repository storage add` to always have the `--endpoint-url` parameter which indicates the usage o MinIO.

2021-09-15 14:15 UTC, lucasncabral requested changes
In some documentation, after the steps to add storage, it is common to show the user how the configuration file should look like. Using MinIO, the endpoint-url field must be filled with what was passed in the command. In the current documentation, the value is `None`.

I noticed this behavior in [first_project ](https://github.com/HPInc/ml-git/blob/98421c6cb40c0e39be25d7aa10934bfacf60ed0a/docs/first_project.md)and [advanced_scenarios](https://github.com/HPInc/ml-git/blob/98421c6cb40c0e39be25d7aa10934bfacf60ed0a/docs/advanced_scenarios.md). But please have a look at the other files.

2021-09-15 16:59 UTC, gilMars approved these changes

2021-09-15 18:41 UTC, lucasncabral approved these changes

2021-09-16 16:51 UTC, andersonpablosilva approved these changes
The branch was reset to not bring duplicated commits into `development` branch.

2021-09-17 12:19 UTC, gpretto approved these changes

2021-09-17 17:35 UTC, merged