Updating docs to teach how to configure MinIO
HPInc/ml-git pull request #161
Opened 2021-09-15 13:05 UTC by GustavoMaciel

Separating the documentation of how to set up S3 in two different files, one for AWS S3 and one for MinIO.

2021-09-15 14:28 UTC, lucasncabral commented on docs/minio_s3_configuration.md
> +# S3 bucket configuration #
```suggestion
# Credentials configuration #
```

2021-09-15 14:28 UTC, lucasncabral commented on docs/minio_s3_configuration.md
> +5. Output Format
To configure MinIO access credentials is it necessary to have the region and output format? I believe this is information for S3 only.

2021-09-15 14:28 UTC, lucasncabral commented on docs/minio_s3_configuration.md
> +## AWS ##
It seems weird to me to have this `AWS` section in the MinIO steps. As well as in a few points, we have `"You can configure AWS in three ways"`. 

I understand that MiniO is an Amazon S3 compatible cloud storage server, so the way to configure the credentials is the same, but maybe adapting the text to make this configuration step clearer for MinIO will make it easier for the user understand.

2021-09-15 14:59 UTC, GustavoMaciel commented on docs/minio_s3_configuration.md
> +# S3 bucket configuration #
Changed in d1aeb2a

2021-09-15 15:01 UTC, GustavoMaciel commented on docs/minio_s3_configuration.md
> +5. Output Format
Removed the Region Name in d1aeb2a, we're not sure if the MinIO actually uses or not the Output Format, so we're leaving it in for now

2021-09-15 15:02 UTC, GustavoMaciel commented on docs/minio_s3_configuration.md
> +## AWS ##
Removed the section AWS and rephrased the sentence in d1aeb2a

2021-09-15 18:33 UTC, gilMars approved these changes

2021-09-15 18:45 UTC, lucasncabral approved these changes

2021-09-16 17:52 UTC, andersonpablosilva requested changes

2021-09-16 17:52 UTC, andersonpablosilva commented on docs/minio_s3_configuration.md
> +$ docker run --name=minio --network=host minio/minio server --console-address ":9001" /data
I believe we should encourage the use of a persistent volume in the command statement (`-v /your/path:/data`) or we could mention it in the text below.

2021-09-16 18:55 UTC, GustavoMaciel commented on docs/minio_s3_configuration.md
> +$ docker run --name=minio --network=host minio/minio server --console-address ":9001" /data
Added to command in 93c00ce

2021-09-16 19:01 UTC, andersonpablosilva approved these changes

2021-09-17 12:24 UTC, gpretto requested changes
Few changes and ideas.

2021-09-17 12:24 UTC, gpretto commented on docs/minio_s3_configuration.md
> +5. Output Format
```suggestion
4. Output Format
```

2021-09-17 12:24 UTC, gpretto commented on docs/storage_configurations.md
> +2. [MinIO](minio_s3_configuration.md)
```suggestion
1. [MinIO](minio_s3_configuration.md)
2. [S3](aws_s3_configuration.md)
```

As we want to provide the MinIO as first options for storage... I will suggest to put as first of this list.

2021-09-17 12:32 UTC, GustavoMaciel commented on docs/minio_s3_configuration.md
> +5. Output Format
Fixed in 175921d

2021-09-17 12:33 UTC, GustavoMaciel commented on docs/storage_configurations.md
> +2. [MinIO](minio_s3_configuration.md)
Changed in 175921d

2021-09-21 13:56 UTC, merged