Adding custom type to validate empty strings and strip values automatically
HPInc/ml-git pull request #164
Opened 2021-09-17 11:58 UTC by GustavoMaciel

params that receive this custom type will have .strip() called on them and will be checked if empty.

`$ ml-git datasets create dataset-ex --mutability=strict --category=imgs --bucket-name=`
Will cause an error and fail the command

`$ ml-git datasets create dataset-ex --mutability=strict --category=imgs --bucket-name="    test_test    "`
will have the storage saved as `s3h://test_test`

2021-09-17 17:33 UTC, gilMars commented on ml_git/utils.py
> +    name = 'trimmed not empty string'
Is it really necessary to use inheritance? I think that you can create a docstring to explain the class goal.

2021-09-17 17:59 UTC, GustavoMaciel commented on ml_git/utils.py
> +    name = 'trimmed not empty string'
The validation in the NotEmptyString will be a common validation that'll be necessary for other params, that's why I made it separately, so it can be reused in future custom types. But in addition to your comment, I also added documentation for both custom types in 354e775.

2021-09-17 18:35 UTC, gilMars approved these changes

2021-09-17 18:49 UTC, lucasncabral approved these changes

2021-09-24 18:49 UTC, lucasncabral requested changes
Keeping in mind that `--bucket-name` is the option to set the name of all supported storage types (S3, Azure, GDrive, SFTP), in some cases we can have a value like "  test_test  " as valid input. If the user is in a linux environment he can even define a folder like: " ". MinIO and GDrive that work with directory systems also allow empty spaces at the beginning and/or end of the name.

In this case, the handling for this option should only validate if the value is not empty (`bucket-name=`).

2021-09-27 12:18 UTC, lucasncabral approved these changes

2021-09-27 14:46 UTC, andersonpablosilva approved these changes

2021-09-27 14:58 UTC, merged