Inserting validation for categories names in --categories option of the ml-git entity create command is used
HPInc/ml-git pull request #169
Opened 2021-09-20 13:28 UTC by talessatiro

Depends on: https://github.com/HPInc/ml-git/pull/164

This PR validates if the categories names (related with --categories option) have a valid Git tag name when the user executes the ml-git entity create command.

If an invalid category name is passed, the following message will be displayed on terminal:

![image](https://user-images.githubusercontent.com/18489870/134009898-7efb8ca9-b77d-4b18-828b-fb1d98b4ad99.png)

2021-09-20 14:52 UTC, gilMars commented on ml_git/commands/custom_types.py
> +        valid_tag_name_regex = r'^(?!\/|@)((?!\/{2,}|\.{2,}|@{)(?=[^[^?*:\\])[(-}])+(?<!\.lock)(?<![/.])$'
move the regex expression to constants.py

2021-09-20 17:01 UTC, talessatiro commented on ml_git/commands/custom_types.py
> +        valid_tag_name_regex = r'^(?!\/|@)((?!\/{2,}|\.{2,}|@{)(?=[^[^?*:\\])[(-}])+(?<!\.lock)(?<![/.])$'
Changed on https://github.com/HPInc/ml-git/pull/169/commits/8bc7a817d417afd3c1788aa5d2119e2c9e49e78b

2021-09-20 17:06 UTC, gilMars approved these changes

2021-09-20 17:21 UTC, lucasncabral approved these changes

2021-09-20 17:21 UTC, lucasncabral commented on ml_git/constants.py
>  RGX_SIZE_FILES = r'[+]\s+size:\s+(\d+(?:[.]\d+)*\s+.+)'
Update header.

2021-09-20 17:26 UTC, talessatiro commented on ml_git/constants.py
>  RGX_SIZE_FILES = r'[+]\s+size:\s+(\d+(?:[.]\d+)*\s+.+)'
Changed on https://github.com/HPInc/ml-git/pull/169/commits/59295481cc64a5de2af0559dc71aa4add8450ae2

2021-09-28 19:54 UTC, andersonpablosilva requested changes

2021-09-28 19:54 UTC, andersonpablosilva commented on tests/integration/test_19_create.py
> +    def test_19_create_labels_with_multiple_categories(self):
Please, fix the sequence for the previous tests.

2021-09-28 19:57 UTC, talessatiro commented on tests/integration/test_19_create.py
> +    def test_19_create_labels_with_multiple_categories(self):
Changed on https://github.com/HPInc/ml-git/pull/169/commits/a0989ff4838de9b9399835f53c03f3d429e4eee9

2021-09-28 20:02 UTC, andersonpablosilva approved these changes

2021-09-28 21:16 UTC, merged