Adding custom type to validate empty strings in entity-dir param of create commend
HPInc/ml-git pull request #170
Opened 2021-09-20 14:58 UTC by Mun1z

params that receive this custom type will have .strip() called on them and will be checked if empty.

`$ ml-git datasets create dataset-ex --mutability=strict --category=imgs --bucket-name="test" --entity-dir=`
Will cause an error and fail the command

2021-09-20 17:09 UTC, lucasncabral reviewed
The PR description says:
```
params that receive this custom type will have .strip() called on them and will be checked if empty.
```
The type `NotEmptyString` applied to the option does not perform the strip. The `NotEmptyString`  type will validate the received value and check if it's an empty string. Please check if the treatment performed is the desired one.

Also, add tests to validate the fix.

2021-09-20 19:42 UTC, Mun1z commented on ml_git/commands/descriptor.py
> +            '--entity-dir': {'type': NotEmptyString(),'default': '', 'help': help_msg.ENTITY_DIR}
The PR description has updated.
The default value has changes to '.', and has added a treatment for this default value on directory creation.

2021-09-22 13:02 UTC, GustavoMaciel requested changes
The chosen implementation was a little off from the python standards, so I left a few suggestions on how the same thing could be accomplished in more of a python way.

2021-09-22 16:58 UTC, lucasncabral commented on ml_git/commands/descriptor.py
> +            '--entity-dir': {'type': NotEmptyString(),'default': '', 'help': help_msg.ENTITY_DIR}
Please take a look at the comments @GustavoMaciel posted.

2021-09-24 18:39 UTC, Mun1z commented on ml_git/config.py
> +
Done on last commit.

2021-09-24 18:39 UTC, Mun1z commented on ml_git/commands/descriptor.py
> +            '--entity-dir': {'type': NotEmptyString(),'default': '.', 'help': help_msg.ENTITY_DIR}
Done on last commit.

2021-09-24 18:39 UTC, Mun1z commented on ml_git/config.py
>                                      imported_dir, mutability, entity_dir=''):
Done on last commit.

2021-09-27 12:16 UTC, lucasncabral requested changes
Please fix the warning pointed out by flake8:

```
./tests/integration/test_19_create.py:300:107: W292 no newline at end of file
                      + ' --categories=img --mutability=' + STRICT + ' --bucket-name=test --entity-dir='))                                                                                                          ^
1     W292 no newline at end of file
1
```

Also, an integration test is failing:
```
================================= FAILURES =================================
__________ CreateAcceptanceTests.test_12_create_with_unzip_option __________

```

And update the branch to resolve the conflicts.

2021-09-28 17:16 UTC, GustavoMaciel approved these changes

2021-09-28 17:16 UTC, GustavoMaciel commented on ml_git/config.py
> +
Remove file alteration or update Copyright header

2021-09-28 17:30 UTC, lucasncabral approved these changes

2021-09-28 19:55 UTC, andersonpablosilva approved these changes

2021-09-29 01:32 UTC, merged