Applying logic to remove whitespaces in standart wizard input
HPInc/ml-git pull request #230
Opened 2022-06-23 14:20 UTC by MatheusClaudi

2022-06-27 12:52 UTC, Vieira-Carlos commented on ml_git/commands/wizard.py
> +            new_field = check_empty_for_none(request_new_value(input_message, required, type).strip())
Is it guaranteed that "request_new_value" here will never return None ?

2022-06-27 12:58 UTC, lucasncabral requested changes
Remember to add tests.

2022-06-27 12:58 UTC, lucasncabral commented on ml_git/commands/wizard.py
> +            new_field = check_empty_for_none(request_new_value(input_message, required, type).strip())
In cases like the port option in the add store command that the type is integer the strip will result in an error, won't it?

2022-06-29 11:48 UTC, MatheusClaudi commented on ml_git/commands/wizard.py
> +            new_field = check_empty_for_none(request_new_value(input_message, required, type).strip())
Yes, always will be returned a string, even when the user just presses enter, without digit anything.

2022-06-29 11:51 UTC, MatheusClaudi commented on ml_git/commands/wizard.py
> +            new_field = check_empty_for_none(request_new_value(input_message, required, type).strip())
Actually will not because the function click. prompt always will read a string, but to make sure we can apply a transformation of value to a string.

2022-07-01 11:26 UTC, lucasncabral approved these changes

2022-07-01 12:23 UTC, andersonpablosilva approved these changes

2022-07-01 12:24 UTC, merged