Adding callback to check for empty values in descriptor
HPInc/ml-git pull request #231
Opened 2022-06-23 15:06 UTC by MatheusClaudi

2022-06-27 12:42 UTC, Vieira-Carlos commented on tests/integration/test_03_add_store.py
> +                                   ('{} --region=notaregion{}'.format(BUCKET_NAME, ' --type=sftph --port=' + invalid_port))))
What happens when the "region" option here is empty?

>--region= --type=sftph

2022-06-27 13:02 UTC, lucasncabral requested changes
The solution is correct, however I believe that we should apply this solution to all options, since none should allow the empty value (as far as I can remember).

For this we can investigate a way to apply this callback to all options.

2022-06-29 12:53 UTC, Vieira-Carlos commented on ml_git/commands/descriptor.py
> +            value['callback'] = partial(multiple_option_callback, callbacks)
👍

2022-06-30 16:23 UTC, lucasncabral approved these changes

2022-06-30 18:20 UTC, Vieira-Carlos approved these changes

2022-07-01 12:09 UTC, andersonpablosilva approved these changes

2022-07-01 12:09 UTC, merged