Adding wizard to command storage del
HPInc/ml-git pull request #235
Opened 2022-06-30 12:30 UTC by MatheusClaudi

2022-06-30 16:20 UTC, lucasncabral requested changes
Remember to add tests for the developed scenarios.

2022-06-30 18:41 UTC, Vieira-Carlos approved these changes

2022-06-30 18:46 UTC, lucasncabral commented on docs/mlgit_commands.md
> +  --wizard                        Enable the wizard to prompt the user requesting information when needed.
```suggestion
  -g, --global                    Use this option to set configuration at
                                  global level
  --wizard                        Enable the wizard to prompt the user 
                                  requesting information when needed.
```

2022-07-01 12:40 UTC, lucasncabral commented on tests/integration/test_03_add_store.py
> +                      check_output(MLGIT_STORAGE_DEL % BUCKET_NAME + ' --wizard'))
We can increment this test, to validate that the command is correct. In addition to just checking if the message is being passed to the user, we can inform a value and check if the storage was really removed from the file.

2022-07-01 13:58 UTC, lucasncabral commented on docs/mlgit_commands.md
> +  --wizard                        Enable the wizard to prompt the user requesting information when needed.
Suggestion was applied at [9268106](https://github.com/HPInc/ml-git/pull/235/commits/9268106103c2d858b401509f85540c570acc59d5).

2022-07-01 13:58 UTC, lucasncabral commented on tests/integration/test_03_add_store.py
> +                      check_output(MLGIT_STORAGE_DEL % BUCKET_NAME + ' --wizard'))
Tests updated at [0b479a7](https://github.com/HPInc/ml-git/pull/235/commits/0b479a7dfcd973c440c732865e5593c34fb3aea2).

2022-07-01 18:41 UTC, andersonpablosilva commented on docs/mlgit_commands.md
> +  --wizard                        Enable the wizard to prompt the user
Please, update the help message according to 9a4f421 - https://github.com/HPInc/ml-git/pull/237#discussion_r912151927

2022-07-01 19:12 UTC, andersonpablosilva approved these changes

2022-07-01 19:17 UTC, lucasncabral commented on docs/mlgit_commands.md
> +  --wizard                        Enable the wizard to prompt the user
The message was updated at [9da1ccd](https://github.com/HPInc/ml-git/pull/235/commits/9da1ccd25e552f4a44658e4f00d360176b4b567e).

2022-07-01 20:34 UTC, merged