Allowing wizard to activate on parameters with range validation
HPInc/ml-git pull request #248
Opened 2022-07-12 17:31 UTC by MatheusClaudi

2022-07-12 20:22 UTC, MatheusClaudi commented on ml_git/commands/custom_options.py
> +    while callback != len(callbacks):
The descriptor file make sure that callbacks be alwals present as empty in format of a list empty or not, so callbacks len will be in range of 0 to n. But is valid add a restriction to check if callback is passed to avoid problems i  future.

2022-07-13 11:26 UTC, Vieira-Carlos commented on ml_git/commands/descriptor.py
> +                value.pop('validators')
```suggestion
                callbacks = callbacks + value.pop('validators')
```

2022-07-13 12:01 UTC, Vieira-Carlos commented on ml_git/commands/descriptor.py
> +                                                                              partial(check_default_value, default=1)]},
What would happen if we only used "check_integer_value" and "partial(check_default_value)" as the validators here with Wizard enabled? It seems that those two functions can only work together when chained with "check_number_rage" in the middle.

2022-07-13 12:07 UTC, Vieira-Carlos commented on ml_git/commands/custom_options.py
> +        new_value, wizard_been_used = callbacks[callback](ctx, param, current_value)
This will never leave the loop if 'wizard_been_used' is True for the first callback in the list.

2022-07-13 14:26 UTC, MatheusClaudi commented on ml_git/commands/custom_options.py
> +        new_value, wizard_been_used = callbacks[callback](ctx, param, current_value)
It will, because in line 142('current_value = new_value') the value of currente_value will be updated with wizard, so when it check again the same function it will if new_value is valid.

2022-07-13 14:31 UTC, MatheusClaudi commented on ml_git/commands/descriptor.py
> +                                                                              partial(check_default_value, default=1)]},
I've just tested this case and worked

2022-07-13 14:32 UTC, MatheusClaudi commented on ml_git/commands/descriptor.py
> +                                                                              partial(check_default_value, default=1)]},
What did you see to think that?

2022-07-13 14:49 UTC, Vieira-Carlos commented on ml_git/commands/descriptor.py
> +                                                                              partial(check_default_value, default=1)]},
"check_integer_value" seemed to return an empty string '' (due to the default parameter in the call for wizard_for_field being '') and then "check_default_value" would only verify if the value is None. Does the 'value' parameter sent from the 'options' argument resolve to None or '' (empty string) when the user calls the command with wizard activated?

2022-07-13 15:04 UTC, MatheusClaudi commented on ml_git/commands/descriptor.py
> +                                                                              partial(check_default_value, default=1)]},
I get it, but when wizard_for_field is called and the user does not inform anything, it's returned None, not an empty string.

2022-07-18 15:13 UTC, Vieira-Carlos requested changes
Just a small change

2022-07-19 12:38 UTC, MatheusClaudi commented on ml_git/commands/custom_options.py
> +        if numeric_value and not (min <= int(value) <= max):
Fixes

2022-07-19 12:43 UTC, Vieira-Carlos approved these changes

2022-08-12 13:55 UTC, lucasncabral approved these changes

2022-08-12 18:43 UTC, andersonpablosilva commented on ml_git/commands/custom_options.py
> +def check_number_range(ctx, param, value, min, max):
Please, remove `ctx` and `param` parameters, as they are not being used.

2022-08-12 19:41 UTC, MatheusClaudi commented on ml_git/commands/custom_options.py
> +def check_number_range(ctx, param, value, min, max):
These parameters are required to use in callbacks of click Library, so they shouldn't be removed.

2022-08-12 19:46 UTC, andersonpablosilva approved these changes

2022-08-12 19:47 UTC, merged