Changing fsck to recover the corrupt/missing files
HPInc/ml-git pull request #250
Opened 2022-08-11 11:42 UTC by lucasncabral

**fsck clean execution:**
```
$ ml-git datasets fsck
INFO - HashFS: Starting integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]
directories: 100%|█████████████████████████████| 6.00/6.00 [00:00<00:00, 750directories/s]
INFO - HashFS: Finish integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]

INFO - MLGit: Starting integrity check on [D:\demo2\.ml-git\datasets\index]
INFO - MLGit: Finish integrity check on [D:\demo2\.ml-git\datasets\index]

INFO - MLGit: Summary of the results found in the execution:
Total of corrupted files detected: 0.
Total of missing files detected: 0.
Total of fixed files (corrupted and missing): 0
```

**fsck with one blob corrupted:**
```
$ ml-git datasets fsck
INFO - HashFS: Starting integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]
directories: 100%|█████████████████████████████| 6.00/6.00 [00:00<00:00, 854directories/s]
INFO - HashFS: Removing 1 corrupted files
files: 100%|█████████████████████████████| 1.00/1.00 [00:00<00:00, 1.00kfiles/s]
INFO - HashFS: Finish integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]

INFO - MLGit: Starting integrity check on [D:\demo2\.ml-git\datasets\index]
INFO - Local Repository: dataset-ex - 1 missing blob files detected. Download:
files: 100%|█████████████████████████████| 1.00/1.00 [00:01<00:00, 1.52s/files]
INFO - MLGit: Finish integrity check on [D:\demo2\.ml-git\datasets\index]

INFO - MLGit: Summary of the results found in the execution:
Total of corrupted files detected: 1.
Total of missing files detected: 0.
Total of fixed files (corrupted and missing): 1
```

**fsck with one blob missing:**
```
$ ml-git datasets fsck
INFO - HashFS: Starting integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]
directories:  100%|█████████████████████████████| 6.00/6.00 [00:00<00:00, 833directories/s]
INFO - HashFS: Finish integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]

INFO - MLGit: Starting integrity check on [D:\demo2\.ml-git\datasets\index]
INFO - Local Repository: dataset-ex - 1 missing blob files detected. Download:
files: 100%|█████████████████████████████| 1.00/1.00 [00:01<00:00, 1.74s/files]
INFO - MLGit: Finish integrity check on [D:\demo2\.ml-git\datasets\index]

INFO - MLGit: Summary of the results found in the execution:
Total of corrupted files detected: 0.
Total of missing files detected: 1.
Total of fixed files (corrupted and missing): 1
```

**fsck with corrupted file mounted in workspace:**
```
$ ml-git datasets fsck
INFO - HashFS: Starting integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]
directories: 100%|█████████████████████████████| 6.00/6.00 [00:00<00:00, 750directories/s]
INFO - HashFS: Finish integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]

INFO - MLGit: Starting integrity check on [D:\demo2\.ml-git\datasets\index]
INFO - MLGit: Finish integrity check on [D:\demo2\.ml-git\datasets\index]

INFO - MLGit: Summary of the results found in the execution:
Total of corrupted files detected: 1.
Total of missing files detected: 0.
Total of fixed files (corrupted and missing): 0
INFO - MLGit: It has been detected that you have corrupted files in the workspace, you can use the --fix-worskpace option to fix the identified files.
```

**fsck with --fix-workspace:**
```
$ ml-git datasets fsck --fix-workspace
INFO - HashFS: Starting integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]
directories: 100%|█████████████████████████████| 6.00/6.00 [00:00<00:00, 667directories/s]
INFO - HashFS: Finish integrity check on [D:\demo2\.ml-git\datasets\objects\hashfs]

INFO - MLGit: Starting integrity check on [D:\demo2\.ml-git\datasets\index]
INFO - MLGit: Fixing 1 corrupted file(s) found in dataset-ex entity
mounting files in cache: 100%|█████████████████████████████| 1.00/1.00 [00:00<00:00, 200mounting files in cache/s]
mounting files in workspace: 100%|█████████████████████████████| 1.00/1.00 [00:00<00:00, 333mounting files in workspace/s]
INFO - MLGit: Finish integrity check on [D:\demo2\.ml-git\datasets\index]

INFO - MLGit: Summary of the results found in the execution:
Total of corrupted files detected: 1.
Total of missing files detected: 0.
Total of fixed files (corrupted and missing): 1

```

2022-08-12 14:30 UTC, andersonpablosilva commented on ml_git/repository.py
> +        print('')
We need this `print('')` (and the other one bellow)? Can this be resolved in another way?

2022-08-12 14:30 UTC, andersonpablosilva commented on ml_git/ml_git_message.py
> +                              'you can use the --fix-worskpace option to fix the identified files.',
Please, let's change the new and updated messages to use string.format().

2022-08-15 12:53 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +  --fix-workspace  Use this option to repair files identified as corrupt in
```suggestion
  --fix-workspace  Use this option to repair files identified as corrupted in
```

2022-08-15 12:54 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +This command will walk through the internal ml-git directories (index & local repository) and will check the integrity and presence of all blobs under its management.
```suggestion
This command will walk through the internal ml-git directories (index & local repository) and check the presence and integrity of all file blobs under its management.
```

2022-08-15 13:36 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +* Attempts to fetch files detected as corrupt or missing from storage
```suggestion
* Fetch files detected as corrupt or missing from storage
```

2022-08-15 13:37 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +* Checks the integrity of files mounted in the entities workspace
```suggestion
* Check the integrity of files mounted in the entities workspace
```

2022-08-15 13:38 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +* In fix-workspace mode, try to repair corrupted files founded in the entities workspace. A file in the entities workspace is considered corrupted based on the business rule defined by the mutability
```suggestion
* In fix-workspace mode, repair corrupted files found in the entities workspace. A file in the entities workspace is considered 'corrupted' based on the business rule defined by the mutability of the entity. 
```

2022-08-15 13:39 UTC, Vieira-Carlos commented on ml_git/commands/help_msg.py
> +FSCK_FIX_WORKSPACE = 'Use this option to repair files identified as corrupt in the entity workspace.'
```suggestion
FSCK_FIX_WORKSPACE = 'Use this option to repair files identified as corrupted in the entity workspace.'
```

2022-08-15 13:44 UTC, Vieira-Carlos commented on ml_git/ml_git_message.py
> +    'INFO_FINISH_INTEGRITY_CHECK': 'Finish integrity check on [{}]',
```suggestion
    'INFO_FINISH_INTEGRITY_CHECK': 'Finished integrity check on [{}]',
```
Or is it asking the user to finish an integrity check?

2022-08-15 13:46 UTC, Vieira-Carlos requested changes
Some suggestions

2022-08-15 14:49 UTC, Vieira-Carlos approved these changes

2022-08-15 16:36 UTC, lucasncabral commented on docs/mlgit_commands.md
> +* In fix-workspace mode, try to repair corrupted files founded in the entities workspace
Additional text has been added to explain. [14e766f](https://github.com/HPInc/ml-git/pull/250/commits/14e766f3396b6fbe5c4e0a6a302a844c88ef3e3c)

2022-08-15 16:38 UTC, lucasncabral commented on ml_git/repository.py
> +        print('')
`print('')` was used to create blocks in user output. It was refactored to be cleaner. [14e766f](https://github.com/HPInc/ml-git/pull/250/commits/14e766f3396b6fbe5c4e0a6a302a844c88ef3e3c)

2022-08-15 16:39 UTC, lucasncabral commented on docs/mlgit_commands.md
> +  --fix-workspace  Use this option to repair files identified as corrupt in
This and other suggestions were applied in [ca1ee90](https://github.com/HPInc/ml-git/pull/250/commits/ca1ee902e4c995dacd0d80b090c52adc39601444)

2022-08-15 21:29 UTC, andersonpablosilva approved these changes

2022-08-15 21:29 UTC, merged