Adding page of notebook summary
HPInc/ml-git pull request #251
Opened 2022-08-11 12:48 UTC by MatheusClaudi

2022-08-12 11:42 UTC, Vieira-Carlos commented on docs/api/api_scripts/README.md
> +In order to facilitate the learning process of using the ML-Git API, it's offered a series of step-by-step guides that emulate real situations in the learning context using the correct API command se
```suggestion
In order to facilitate the learning process of using the ML-Git API, we offer a series of step-by-step guides that emulate real situations in the learning context applying the correct API command sequences that should be used in each scenario.
```

2022-08-12 11:46 UTC, Vieira-Carlos commented on docs/api/api_scripts/README.md
> +The guides were created using Jupyter notebooks, as their use offers the possibility to run step-by-step code snippets in a format similar to explanatory document, thus becoming ideal for teaching ne
```suggestion
The guides were created using Jupyter notebooks, as they offer the possibility to run, step-by-step, code snippets in a format similar to an explanatory document, thus becoming ideal for teaching new users how to use the api in real case scenarios.
```

2022-08-12 11:58 UTC, Vieira-Carlos commented on docs/api/api_scripts/README.md
> +- [basic_flow](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/basic_flow.ipynb) - This notebook describes a basic flow of ml-git with api. There you will learn how to initialize an ML
```suggestion
- [basic_flow](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/basic_flow.ipynb) - This notebook describes a basic execution flow of ml-git with its api. There, you will learn how to initialize an ML-Git project, how to perform all the necessary configuration steps and how to version a dataset.<br/>
```

2022-08-12 12:01 UTC, Vieira-Carlos commented on docs/api/api_scripts/README.md
> +- [clone_repository](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/clone_repository.ipynb) - This notebook describes how clone a ML-Git repository.
```suggestion
- [clone_repository](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/clone_repository.ipynb) - This notebook describes how to clone an ML-Git repository.
```

2022-08-12 12:02 UTC, Vieira-Carlos commented on docs/api/api_scripts/README.md
> +- [mnist_random_forest_api](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb) - This notebook describes a basic flow with ml-git with api. I
```suggestion
- [mnist_random_forest_api](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb) - This notebook describes a basic execution flow of ml-git with its api. In it, we show how to obtain a dataset already versioned by ml-git, how to perform the versioning process of a model and the new data generated, using the MNIST dataset.
```

2022-08-12 12:05 UTC, Vieira-Carlos commented on docs/api/api_scripts/README.md
> +- [mnist_random_forest_cli](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/mnist_notebook/mnist_random_forest_cli.ipynb) - This notebook describes a basic flow with ml-git. In it, we
```suggestion
- [mnist_random_forest_cli](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/mnist_notebook/mnist_random_forest_cli.ipynb) - This notebook describes a basic execution flow with ml-git. In it, we show how to obtain a dataset already versioned by ml-git, how to perform the versioning process of a model and the new data generated, using the MNIST dataset.
```

2022-08-12 12:05 UTC, Vieira-Carlos commented on docs/api/api_scripts/README.md
> +- [checkout_with_sample](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/multiple_datasets_notebook/checkout_with_sample.ipynb) - This notebook describes how perform a checkout in ML-G
```suggestion
- [checkout_with_sample](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/multiple_datasets_notebook/checkout_with_sample.ipynb) - This notebook describes how to perform a checkout operation with ML-Git using samples of a dataset.
```

2022-08-12 12:06 UTC, Vieira-Carlos commented on docs/api/api_scripts/README.md
> +- [multiple_datasets](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb) - This notebook describes how to handle scenario when the same
```suggestion
- [multiple_datasets](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb) - This notebook describes how to handle the scenario where the same file is present in more than one dataset.
```

2022-08-12 12:07 UTC, Vieira-Carlos requested changes
A few suggestions. Also, it would be good to do the same changes for the notebook's descriptions in each of their files.

2022-08-12 19:46 UTC, Vieira-Carlos approved these changes

2022-08-12 19:52 UTC, andersonpablosilva reviewed
Just a few suggestions

2022-08-12 19:52 UTC, andersonpablosilva commented on docs/api/api_scripts/README.md
> +In order to facilitate the learning process of using the ML-Git API, we offer a series of step-by-step guides that emulate real situations in the learning context applying the correct API command seq
```suggestion
In order to facilitate the learning process of using the ML-Git API, we offer a series of step-by-step guides that emulate real situations in the learning context by applying the correct API command sequences that should be used in each scenario.
```

2022-08-12 19:52 UTC, andersonpablosilva commented on docs/api/api_scripts/README.md
> +The guides were created using Jupyter notebooks, as they offer the possibility to run, step-by-step, code snippets in a format similar to an explanatory document, thus becoming ideal for teaching new
```suggestion
The guides were created using Jupyter notebooks, as they offer the possibility to run, step-by-step, code snippets in a format similar to an explanatory document, thus becoming ideal for teaching new users how to use the API in real case scenarios.
```

2022-08-12 19:52 UTC, andersonpablosilva commented on docs/api/api_scripts/README.md
> +- [basic_flow](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/basic_flow.ipynb) - This notebook describes a basic execution flow of ml-git with its api. There, you will learn how to i
```suggestion
- [basic_flow](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/basic_flow.ipynb) - This notebook describes a basic execution flow of ml-git with its API. There, you will learn how to initialize an ML-Git project, how to perform all the necessary configuration steps and how to version a dataset.<br/>
```

2022-08-12 19:52 UTC, andersonpablosilva commented on docs/api/api_scripts/README.md
> +- [mnist_random_forest_api](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb) - This notebook describes a basic execution flow of ml-git wit
```suggestion
- [mnist_random_forest_api](https://github.com/HPInc/ml-git/blob/main/docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb) - This notebook describes a basic execution flow of ml-git with its API. In it, we show how to obtain a dataset already versioned by ml-git, how to perform the versioning process of a model and the new data generated, using the MNIST dataset.
```

2022-08-12 20:03 UTC, andersonpablosilva approved these changes

2022-08-15 17:15 UTC, lucasncabral approved these changes

2022-08-15 21:25 UTC, merged