Updating the documentation for the add, branch, checkout, commit and create commands
HPInc/ml-git pull request #287
Opened 2022-11-18 12:07 UTC by lucasncabral

2022-11-18 12:20 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +To successfully execute the command, it is expected that the informed entity <ml-entity-name> to be a directory under the tree structure and ML-Git will search for it in the tree.
```suggestion
To successfully execute the command, it is expected that the informed entity <ml-entity-name> is a directory under the tree structure and ML-Git will search for it in the tree. 
```

2022-11-18 12:21 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +Under that repository, it is also expected to have a <ml-entity-name>.spec file (created with ml-git create command) , defining the ML entity to be added.
```suggestion
Under that repository, it is also expected that an <ml-entity-name>.spec file (created with ml-git create command) exists, defining the ML entity to be added.
```

2022-11-18 12:24 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +With this command you will download the files belonging to that entity in the version specified in the command.
```suggestion
With this command you will download the files belonging to that entity from the version specified in the command.
```

2022-11-18 12:24 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +```-d, --with-dataset:``` It can only be used in checkout of labels and models to get the entities that are associated with the entity.
```suggestion
```-d, --with-dataset:``` It can only be used in the checkout of labels and models to get the other entities that are associated with this entity.
```

2022-11-18 12:25 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +```-l, --with-labels:``` It can only be used in checkout of models to get the label entity that are associated with the entity.
```suggestion
```-l, --with-labels:``` It can only be used in the checkout of models to get the label entities that are associated with the model.
```

2022-11-18 12:28 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +Internally, ML-Git keeps track of files that have been added to the data storage and is storing that information to the metadata management layer to be able to restore any version of each \<ml-entity
```suggestion
Internally, ML-Git keeps track of files that have been added to the data storage and stores that information in the metadata management layer, allowing it to restore any version of each \<ml-entity-name\>.
```

2022-11-18 12:29 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +```--dataset:``` These options are available for labels e model. ML-Git will inspect the HEAD/ref of the specified \<dataset-name\> checked out in the ml-git repository and will add that information
```suggestion
```--dataset:``` These options are available for labels and models. ML-Git will inspect the HEAD/ref of the specified \<dataset-name\> checked out in the ml-git repository and will add that information to the specification file that is committed in the metadata repository.
```

2022-11-18 12:32 UTC, Vieira-Carlos requested changes
A few suggestions

2022-11-18 12:46 UTC, Vieira-Carlos approved these changes

2022-11-24 13:35 UTC, andersonpablosilva commented on docs/mlgit_commands.md
> +With this command you will download the files belonging to that entity from the version specified in the command.
```suggestion
With this command, you will download the files belonging to that entity from the version specified in the command.
```

2022-11-24 14:17 UTC, andersonpablosilva approved these changes

2022-11-24 14:19 UTC, merged