Updating commands documentation
HPInc/ml-git pull request #288
Opened 2022-11-22 16:07 UTC by lucasncabral

2022-11-22 18:56 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +The ```--stat``` and ```--fullstat``` must be used when the user wants to bring more information in the log of each tag of the entity.
```suggestion
The ```--stat``` and ```--fullstat``` must be used when the user wants to show more information in the logs for each tag of the entity.
```

2022-11-22 19:01 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +The options of this command allow the user to configure its behavior in case of failures. During the process of sending blobs, if it fails, ML-Git tries to send the same blob the amount informed in t
```suggestion
The options of this command allow the user to configure its behavior in case of failures. During the process of sending blobs, if it fails, ML-Git attempts at most 'N' times to send the same blob again, with 'N' being the value informed in the ```retry``` option. However, even if the upload of that blob fails after reaching said limit, the command will still continue to send the other blobs.
```

2022-11-22 19:05 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +This command will clone the configuration repository and initialize all necessary configurations for ML-Git to work properly. After this command, you can directly use the checkout command for example
```suggestion
This command will clone the configuration repository and setup the initial configuration that is necessary for ML-Git to work properly. After executing this command, you can directly use the checkout command, for example, without having to initialize each type of entity.
```

2022-11-22 19:07 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +Use this command if you want to check what configuration ml-git is running with. It is highly likely one will need to change the default configuration to adapt for her needs.
```suggestion
Use this command if you want to check what configuration ml-git is running with. It is highly likely that a user will need to change the default configuration to adapt ml-git for their needs.
```

2022-11-22 19:07 UTC, Vieira-Carlos commented on docs/mlgit_commands.md
> +This command allows the user to configure the type of storage he needs. Therefore, some options are specific to some storage types, namely:
```suggestion
This command allows the user to configure the type of storage they need. Therefore, some options are specific to some storage types, namely:
```

2022-11-22 19:08 UTC, Vieira-Carlos requested changes
A few suggestions

2022-11-23 11:31 UTC, Vieira-Carlos approved these changes

2022-11-24 12:30 UTC, andersonpablosilva commented on docs/mlgit_commands.md
> +The options of this command allow the user to configure its behavior in case of failures. During the process of sending blobs, if it fails, ML-Git attempts at most 'N' times to send the same blob aga
```suggestion
The options of this command allow the user to configure its behavior in case of failures. During the process of sending blobs, if it fails, ML-Git attempts 'N' times to send the same blob again, with 'N' being the value informed in the ```retry``` option. However, even if the upload of that blob fails after reaching the said limit, the command will still continue to send the other blobs.
```

2022-11-24 12:30 UTC, andersonpablosilva commented on docs/mlgit_commands.md
> +You should only use this command for the flexible mutability option.
```suggestion
You should only use this command in an entity configured with `flexible` mutability option. 
```

2022-11-24 13:36 UTC, andersonpablosilva approved these changes

2022-11-24 14:17 UTC, merged