Adding plural entity names support
HPInc/ml-git pull request #30
Opened 2020-09-29 21:02 UTC by andersonpablosilva

Adding plural entity names support (`datasets`, `labels`and `models`). Singular entity names are now deprecated (`dataset` and `model`).

2020-09-30 19:25 UTC, lucianoalves requested changes
Why we are using dataset in there:
https://github.com/HPInc/ml-git/blob/80c8bf574fb658bad2d741d9d6ce9f24fafaace1/ml_git/repository.py#L38

2020-09-30 19:25 UTC, lucianoalves commented on docs/api/api_scripts/checkout_with_sample.ipynb
> +  },
Is it related pyCharm. I am not sure if it is necessary.

2020-10-01 14:18 UTC, lucasncabral commented
> Why we are using dataset in there:
> https://github.com/HPInc/ml-git/blob/80c8bf574fb658bad2d741d9d6ce9f24fafaace1/ml_git/repository.py#L38

The use of entities in the plural was a modification made in the CLI to facilitate the execution of commands by users.
 
Internally ml-git continues to use the 'dataset' and 'model' keys to maintain backward compatibility. Bearing in mind some points:

- metadata directories are written in .ml-git/(dataset|model|labels); 
- entities are stored inside the dataset|model|labels folder at the root of the project;
- the spec file has a key for the type of entity in the singular;
- the config file has the remote keys with the entities in the singular.

2020-11-19 14:34 UTC, andersonpablosilva commented
Closing this PR, since this feature is on hold.

2020-11-19 14:34 UTC, closed without merging