Adding mandatory option to set mutability during entity creation
HPInc/ml-git pull request #37
Opened 2020-10-09 00:35 UTC by andersonpablosilva

We added the `--mutability` option to the `ml-git create` command, needed to set mutability during entity creation.

2020-10-09 12:30 UTC, carlosEleao reviewed
Please adjust the mutability that is recommended for creating a image dataset.

2020-10-09 12:30 UTC, carlosEleao commented on README.md
> +$ ml-git dataset create --category=computer-vision --category=images --bucket-name=your_bucket --import=../import-path --mutability=mutable dataset-ex
since this repository is with the category images and it is for computer vision the mutability recommended should be strict

2020-10-09 12:30 UTC, carlosEleao commented on docs/first_project.md
> +$ ml-git dataset create imagenet8 --category=computer-vision --category=images --mutability=mutable --store-type=s3h --bucket-name=mlgit-datasets --version=1
Mutability strict as well. We should recommend flexible/mutable only for tabular data.

2020-10-09 16:22 UTC, carlosEleao approved these changes

2020-10-19 18:55 UTC, diego-pedroso approved these changes

2020-10-19 18:56 UTC, diego-pedroso requested changes
---

2020-10-19 18:56 UTC, diego-pedroso approved these changes

2020-10-21 17:14 UTC, merged