Modifying the status command to receive a directory path as an argument
HPInc/ml-git pull request #50
Opened 2020-11-10 19:51 UTC by Mun1z

Directory path argument on status command to show only files inside directory. 
Example:  `ml-git dataset status imagenet8`
```
INFO - Repository: dataset: status of ml-git index for [dataset-ex]
Changes to be committed:
Untracked files:
        README.md
        imagenet8.spec
        data\file1.jpg
Corrupted files:
```
with argument  on command: `ml-git dataset status imagenet8 data`

```
INFO - Repository: dataset: status of ml-git index for [dataset-ex]
Changes to be committed:
Untracked files:
        file1.jpg
 Corrupted files:
```

2020-11-12 20:06 UTC, lucasncabral requested changes

2020-11-12 20:06 UTC, lucasncabral commented on tests/integration/test_36_status_path_directory.py
> +                         r'Changes to be committed:\s+Untracked files:(\s|.)*file3(\s|.)*file4(\s|.)')
Could you create more test scenarios for the command? For example:

- Status passing a directory that does not exist.
- Status of a directory after executing the ml-git add command

2020-11-13 13:00 UTC, Mun1z commented on ml_git/file_system/local.py
> +        new_files, deleted_files, untracked_files, _, _ = self.status(spec_name, status_directory="", log_errors=False)
Done.

2020-11-13 13:00 UTC, Mun1z commented on docs/mlgit_commands.md
>  Example:
Done.

2020-11-13 13:03 UTC, Mun1z commented on tests/integration/test_36_status_path_directory.py
> +class StatusShortModeAcceptanceTests(unittest.TestCase):
Done.

2020-11-13 21:41 UTC, Mun1z commented on ml_git/file_system/local.py
> +    def status(self, spec, status_directory="", log_errors=True):
Done on commit [1f90927](https://github.com/HPInc/ml-git/pull/50/commits/1f90927a4a232892ab9ad9670ce8e91e24096d64)

2020-11-13 22:40 UTC, Mun1z commented on tests/integration/test_36_status_path_directory.py
> +                         r'Changes to be committed:\s+Untracked files:(\s|.)*file3(\s|.)*file4(\s|.)')
Done.

2020-11-16 19:54 UTC, gilMars commented on tests/integration/test_35_status_short_mode.py
> +        os.chmod(file_to_be_deleted, S_IWUSR | S_IREAD)
Use clear function in defined in helper.py

2020-11-17 17:01 UTC, Mun1z commented on tests/integration/test_35_status_short_mode.py
> +        os.chmod(file_to_be_deleted, S_IWUSR | S_IREAD)
Done on commit [529de97](https://github.com/HPInc/ml-git/pull/50/commits/529de9770f269d9784f919fa0d2c7b1bffd61e89)

2020-11-17 17:29 UTC, andersonpablosilva approved these changes

2020-11-17 17:31 UTC, gilMars approved these changes

2020-11-17 17:37 UTC, lucasncabral approved these changes

2020-11-20 21:16 UTC, diego-pedroso approved these changes

2020-11-20 21:42 UTC, merged