Changing log command to show informations about specialized data.
HPInc/ml-git pull request #65
Opened 2020-12-11 11:51 UTC by gilMars

If you have a data specialization plugin installed and properly confiure, the log command will show extra information about the specialized data.

Output example:
```
ml-git dataset log dataset-ex
INFO - Repository: 

Tag: parquet__dataset-ex__1
Author: Author
Email: youremail@example.com
Date: 2020-12-08 14:10:52
Message: parquet/dataset-ex
Files:
        parquet: ROWS: 10 | COLUMNS: 8

Tag: parquet__dataset-ex__2
Author: Author
Email: youremail@example.com
Date: 2020-12-08 16:11:06
Message: parquet/dataset-ex
Files:
        parquet: ROWS: 11 | COLUMNS: 8

        ++++++++++ Insertions ++++++++++
              [ROWS: 1] | [COLUMNS: 0]
```

2020-12-11 12:40 UTC, Mun1z requested changes
The "new_log_info" variable, it is not very clear what it really is, could you put a more intuitive name?

2020-12-11 13:23 UTC, gilMars commented
> The "new_log_info" variable, it is not very clear what it really is, could you put a more intuitive name?

Changed in commit 332514d

2020-12-11 15:03 UTC, Mun1z approved these changes

2020-12-15 12:40 UTC, lucasncabral commented on docs/plugins.md
> +Responsible for displaying a formatted output containing, the number of rows and columns of the versioned tabular data,  and the amount of insertions or deletions between each version.
This document should describe the contract for the development of a plugin. This description provided directly targets a plugin that handles tabular data, but may not be the case. Please add a more general description.

Another question that has arisen is whether the display is made directly by the plugin or if it returns the information to ml-git to format and present it in the manner mentioned in the description.

2020-12-15 12:40 UTC, lucasncabral commented on ml_git/_metadata.py
> +    def get_log_info(self, spec, new_info=None, fullstat=False):
Please rename "new_info" variable to a more intuitive name. Also keep the order of the parameters that already existed, adding the new one at the end.

2020-12-15 12:40 UTC, lucasncabral commented on ml_git/_metadata.py
> +    def _parse_tag_to_path(tag):
Apparently, this method doesn't just turn the tag into a path. It is returning the path to an entity's spec file. If so, why not use the `spec.search_spec_file` or `utils.get_path_with_categories` method?

2020-12-17 11:33 UTC, lucasncabral commented on docs/plugins.md
> +Responsible for displaying a formatted output containing, the number of rows and columns of the versioned tabular data,  and the amount of insertions or deletions between each version.
Done in 1e416f2

2020-12-17 11:33 UTC, lucasncabral commented on ml_git/_metadata.py
> +    def get_log_info(self, spec, new_info=None, fullstat=False):
Done in 1e416f2

2020-12-17 11:33 UTC, lucasncabral commented on ml_git/_metadata.py
> +    def _parse_tag_to_path(tag):
Done in 1e416f2

2020-12-17 11:34 UTC, lucasncabral approved these changes

2020-12-17 12:26 UTC, andersonpablosilva approved these changes

2021-01-14 18:21 UTC, diego-pedroso approved these changes

2021-01-15 10:36 UTC, merged