Implementation of sftp storage
HPInc/ml-git pull request #68
Opened 2021-01-13 14:40 UTC by Mun1z

The sftp protocol storage was implemented, but the unit and integration tests will be added in a different pull request.

2021-01-13 19:36 UTC, lucasncabral requested changes
Please take a look at the commented points. In addition, add documentation related to this new type of storage in docs/storage_configurations.md. Also update the documentation of the commands that were affected (storage add, storage del, create).

2021-01-13 19:36 UTC, lucasncabral commented on ml_git/constants.py
> +    SFTP = 'sftp'
Is it necessary to define the `sftp` type? Currently the implementation only supports the `sftph` (with the files breaking).

2021-01-13 19:36 UTC, lucasncabral commented on ml_git/storages/sftp_store.py
> +        self._store_type = 'SFTP'
Why not use the value defined in the enum? (`StoreType.SFTPH.value`)

2021-01-13 19:36 UTC, lucasncabral commented on ml_git/storages/sftp_store.py
> +        mykey = paramiko.RSAKey.from_private_key_file(self._key)
Please rename `mykey` variable to a more intuitive name (`user_key`?).

2021-01-13 19:36 UTC, lucasncabral commented on ml_git/storages/sftp_store.py
> +    def create_bucket_name(self, bucket_prefix):
This method is duplicated (`storages/s3store.create_bucket_name`). I think the ideal would be to move it to the `storages/store_utils.py` file.

2021-01-13 19:36 UTC, lucasncabral commented on ml_git/storages/sftp_store.py
> +        log.info('Put - stored [%s] in bucket [%s] with key [%s]-[%s]' % (file_path, bucket, key_path, version),
Please place this message in the `ml_git_messages.py` file.

2021-01-13 19:36 UTC, lucasncabral commented on ml_git/storages/sftp_store.py
> +    def get_object(self, key_path):
I couldn't understand the logic of this method. Why do we need a 'try' block to throw an exception? And why catch an exception of a different type than the one that was thrown? Is this code block really necessary? 

Apparently it is always returning the exception that the object was not found.

2021-01-13 19:36 UTC, lucasncabral commented on ml_git/storages/sftp_store.py
> +    def _get(self, file, key_path, version=None):
The same comment made above.

2021-01-14 00:26 UTC, Mun1z commented on ml_git/storages/sftp_store.py
> +    def _get(self, file, key_path, version=None):
Resolved on commit: [6354d28](https://github.com/HPInc/ml-git/pull/68/commits/6354d28410904663ae41f8028037197034fa34f5)

2021-01-14 00:26 UTC, Mun1z commented on ml_git/storages/sftp_store.py
> +    def get_object(self, key_path):
Resolved on commit: [6354d28](https://github.com/HPInc/ml-git/pull/68/commits/6354d28410904663ae41f8028037197034fa34f5)

2021-01-14 00:26 UTC, Mun1z commented on ml_git/storages/sftp_store.py
> +        log.info('Put - stored [%s] in bucket [%s] with key [%s]-[%s]' % (file_path, bucket, key_path, version),
Resolved on commit: [6354d28](https://github.com/HPInc/ml-git/pull/68/commits/6354d28410904663ae41f8028037197034fa34f5)

2021-01-14 00:27 UTC, Mun1z commented on ml_git/storages/sftp_store.py
> +    def create_bucket_name(self, bucket_prefix):
This generate a circular dependency.

2021-01-14 00:27 UTC, Mun1z commented on ml_git/storages/sftp_store.py
> +        mykey = paramiko.RSAKey.from_private_key_file(self._key)
Resolved on commit: [6354d28](https://github.com/HPInc/ml-git/pull/68/commits/6354d28410904663ae41f8028037197034fa34f5)

2021-01-14 00:27 UTC, Mun1z commented on ml_git/storages/sftp_store.py
> +        self._store_type = 'SFTP'
Resolved on commit: [6354d28](https://github.com/HPInc/ml-git/pull/68/commits/6354d28410904663ae41f8028037197034fa34f5)

2021-01-14 00:28 UTC, Mun1z commented on ml_git/constants.py
> +    SFTP = 'sftp'
Resolved on commit: [6354d28](https://github.com/HPInc/ml-git/pull/68/commits/6354d28410904663ae41f8028037197034fa34f5)

2021-01-14 14:25 UTC, lucasncabral approved these changes

2021-01-14 14:44 UTC, GustavoMaciel approved these changes

2021-01-14 17:35 UTC, gilMars approved these changes

2021-01-14 22:09 UTC, andersonpablosilva requested changes

2021-01-15 14:08 UTC, Mun1z commented on ml_git/admin.py
> +def store_add(store_type, bucket, credentials_profile, global_conf=False, endpoint_url=None, username=None, ssh_key=None):
Done on commit [937ebcb](https://github.com/HPInc/ml-git/pull/68/commits/937ebcb6ef4486a8470ad33477acbf855039e533)

2021-01-15 22:02 UTC, andersonpablosilva approved these changes

2021-01-21 17:53 UTC, diego-pedroso commented on tests/integration/fake_ssh_key/id_rsa
> +-----BEGIN OPENSSH PRIVATE KEY-----
Can't we generate this key using CLI before the test execution?

2021-01-21 17:54 UTC, diego-pedroso commented on docs/sftp_configurations.md
> +This section explains how to configure the settings that the ml-git uses to interact with your bucket using the SFTP storage. This requires you to have configured a public key in your SFTP server and
Is 'bucket' also a terminology used on SFTP servers, or are we using 'bucket' to define repositories/directories on all storage services?

2021-01-21 18:52 UTC, Mun1z commented on docs/sftp_configurations.md
> +This section explains how to configure the settings that the ml-git uses to interact with your bucket using the SFTP storage. This requires you to have configured a public key in your SFTP server and
In this case we are using it to define the repositories/directories of any service.

2021-01-22 18:33 UTC, Mun1z commented on tests/integration/fake_ssh_key/id_rsa
> +-----BEGIN OPENSSH PRIVATE KEY-----
Yes, the change was made to generate the key via the command line during the execution of the tests.

2021-01-22 19:19 UTC, diego-pedroso approved these changes

2021-01-22 20:13 UTC, merged