Adding support to plural entity names
HPInc/ml-git pull request #69
Opened 2021-01-13 18:46 UTC by lucasncabral

The ml-git code has been modified to work with `datasets`, `models `and `labels`.

```
ml-git --help

Usage: ml-git [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.

Commands:
  clone       Clone a ml-git repository ML_GIT_REPOSITORY_URL
  datasets    Management of datasets within this ml-git repository.
  labels      Management of labels sets within this ml-git repository.
  models      Management of models within this ml-git repository.
  repository  Management of this ml-git repository.
```

Logic has also been added to allow automatic updating of an old project. This logic changes the directories of the current project, the keys in the config file and also in the spec file of each entity.

**Example:** 

User workspace:
```
project/
├── dataset
│   └── dataset-ex1
├── labels
│   └── labels-ex1
├── model
│   └── model-ex1
├── .ml-git
│   ├── dataset
│   ├── model
│   ├── label
│   └── config
└── imagenet8.spec
```

Execute any command:
```
> ml-git datasets add dataset-ex
> INFO - MLGit: It was observed that the directories of this project follow the scheme of old versions of ml-git.
>         To continue using this project it is necessary to update the directories.
>         Do you want to update your project now? (Yes/No) Yes
> INFO - MLGit: Project updated successfully
```

After update:
```
project/
├── datasets <- Change here
│   └── dataset-ex1
├── labels
│   └── labels-ex1
├── models <- Change here
│   └── model-ex1
├── .ml-git
│   ├── datasets <- Change here
│   ├── models <- Change here
│   ├── label
│   └── config
└── imagenet8.spec
```

2021-01-14 12:11 UTC, Mun1z approved these changes

2021-01-14 12:59 UTC, gilMars commented on ml_git/commands/entity.py
> +def dataset(ctx):
Could change the function name `def dataset(ctx)` to `def datasets(ctx)`?

2021-01-14 12:59 UTC, gilMars commented on ml_git/commands/entity.py
> +def model(ctx):
Could change the function name `def model(ctx)` to `def models(ctx)`?

2021-01-14 13:01 UTC, gilMars commented on ml_git/config.py
> +    'datasets': {
Why not use the Enum EntityType?

2021-01-14 13:02 UTC, gilMars commented on ml_git/config.py
> +    'models': {
The same as above.

2021-01-14 13:03 UTC, gilMars commented on ml_git/config.py
> +        'models': mlgit_config['models'],
Why not use the Enum EntityType?

2021-01-14 13:05 UTC, gilMars commented on ml_git/config.py
> +def get_metadata_path(config, type=EntityType.DATASETS.value):
Could you use the same value for the other functions?

2021-01-14 13:08 UTC, gilMars commented on ml_git/repository.py
> +                self.__repo_type = 'datasets'
Use the enum EntityType.

2021-01-14 13:10 UTC, gilMars commented on ml_git/utils.py
> +    if 'dataset' in hash:
Assign the value to a variable or use a constant if necessary..

2021-01-14 13:17 UTC, gilMars commented on ml_git/utils.py
> +    except Exception as e:
I guess that you can use the RootPathException:
```
try:
    root_path = get_root_path()
except RootPathException:
    return
```

2021-01-14 13:19 UTC, gilMars commented on ml_git/utils.py
> +    have_old_dataset_path = os.path.exists(os.path.join(root_path, 'dataset')) or os.path.exists(os.path.join(root_path, '.ml-git', 'dataset'))
use the constant ROOT_FILE_NAME instead '.ml-git'.

2021-01-14 13:22 UTC, gilMars commented on ml_git/utils.py
> +        log.info('It was observed that the directories of this project follow the scheme of old versions of ml-git.\n' +
Transfer the log message to ml_git_message.py if possible.

2021-01-14 14:10 UTC, GustavoMaciel requested changes
Take a look at the comments I've made and see if they make sense for you as well

2021-01-14 14:10 UTC, GustavoMaciel commented on ml_git/commands/utils.py
> +def init_repository(entity_type='datasets'):
```suggestion
def init_repository(entity_type=DATASETS):
```
Perhaps it's better to get rid of any hardcoded value as we have the opportunity

2021-01-14 14:10 UTC, GustavoMaciel commented on ml_git/repository.py
> +            dataset_tag = get_entity_tag(spec_path, repo_type, 'datasets')
Use a constant instead of the hardcoded value here and in the code below

2021-01-14 14:54 UTC, GustavoMaciel approved these changes

2021-01-14 20:26 UTC, gilMars approved these changes

2021-01-21 17:57 UTC, diego-pedroso commented on ml_git/commands/general.py
>      pass
I believe this line can be removed now.

2021-01-21 20:11 UTC, lucasncabral commented on ml_git/commands/general.py
>      pass
The line was removed in 427b2f7.

2021-01-21 20:53 UTC, diego-pedroso approved these changes

2021-01-22 18:08 UTC, merged