Removing deprecated version-number option
HPInc/ml-git pull request #75
Opened 2021-01-21 12:52 UTC by lucasncabral

This change affects the `ml-git commit` and `ml-git create` commands. The user must use the `--version` option.

```
Usage: ml-git dataset commit [OPTIONS] ML_ENTITY_NAME

  Commit dataset change set of ML_ENTITY_NAME locally to this ml-git
  repository.

Options:
  --tag TEXT               Ml-git tag to identify a specific version of a ML
                           entity.
  --version INTEGER RANGE  Set the number of artifact version.
  -m, --message TEXT       Use the provided <msg> as the commit message.
  --fsck TEXT              Run fsck after command execution.
  --verbose                Debug mode
```

2021-01-21 14:56 UTC, andersonpablosilva requested changes

2021-01-21 14:56 UTC, andersonpablosilva commented on docs/mlgit_commands.md
> +  --version INTEGER RANGE         Set the number of artifact version.
Why are we specifying an INTEGER RANGE? Maybe you should use just INTEGER.

2021-01-21 14:56 UTC, andersonpablosilva commented on docs/mlgit_commands.md
> +  --version INTEGER RANGE         Number of artifact version.
Check previous comment about INTEGER RANGE.

2021-01-21 14:56 UTC, andersonpablosilva commented on tests/integration/test_06_commit_files.py
> +        self.assertIn(messages[106] % '--version-number', result)
Maybe we should use the new output_messages list. We should avoid changing or adding messages to the old indexed messages list.

Note: this comment also applies to the following places: 
- tests/integration/output_messages.py: L105, L115
- tests/integration/test_19_create.py: L186

2021-01-21 15:06 UTC, lucasncabral commented on docs/mlgit_commands.md
> +  --version INTEGER RANGE         Set the number of artifact version.
As we use the tag to generate a reference file for ml-git, a tag with a very long version ends up causing errors when trying to generate this file.

In an initial version we worked without defining the range, but it was corrected in PR #25 to deal with the range of a number of up to 9 places.

2021-01-21 15:08 UTC, lucasncabral commented on docs/mlgit_commands.md
> +  --version INTEGER RANGE         Number of artifact version.
Answered in the previous comment, please take a look.

2021-01-21 17:07 UTC, Mun1z approved these changes

2021-01-21 18:28 UTC, GustavoMaciel approved these changes

2021-01-21 20:23 UTC, andersonpablosilva commented on docs/mlgit_commands.md
> +  --version INTEGER RANGE         Set the number of artifact version.
Ok, I got it. In this case we can improve the help description and make it clear that this is a range of allowed values.

2021-01-21 21:08 UTC, lucasncabral commented on tests/integration/test_06_commit_files.py
> +        self.assertIn(messages[106] % '--version-number', result)
This and the other messages were sent to the new output_messages list in 89ae397.

2021-01-21 21:09 UTC, lucasncabral commented on docs/mlgit_commands.md
> +  --version INTEGER RANGE         Set the number of artifact version.
The help message for this option was modified on 89ae397. New message: 

> Set the version number of the artifact. This number must be in the range 0 to 999999999.

2021-01-22 10:35 UTC, gilMars approved these changes

2021-01-22 18:14 UTC, andersonpablosilva approved these changes

2021-01-22 19:50 UTC, diego-pedroso approved these changes

2021-01-22 20:17 UTC, merged