[redefine storage setup] Redefining setup cloud storage link (store/storage)
HPInc/ml-git pull request #76
Opened 2021-01-21 14:03 UTC by lucasncabral

The ml-git code has been modified to work with `storage` instead of `store`.  Deprecated `store` commands have been removed. The user must use `storage`.

```
Usage: ml-git repository [OPTIONS] COMMAND [ARGS]...

  Management of this ml-git repository.

Options:
  --help  Show this message and exit.

Commands:
  config   Configuration of this ml-git repository
  gc       Cleanup unnecessary files and optimize the use of the disk space.
  init     Initialiation of this ml-git repository
  remote   Configure remote ml-git metadata repositories.
  storage  Storage management for this ml-git repository.
  update   This command will update all ml-entities metadata repository.
```

Logic has also been added to allow automatic updating of an old project. This logic changes the keys that link to the storage in the entitiy config and spec files.

Config and spec:

```
dataset:
  git: ''
model:
  git: ''
storage: <- Changed from store to storage here
  s3:
    mlgit-datasets:
      aws-credentials:
        profile: default
      region: us-east-1
```

```
dataset:
  categories:
  - test
  manifest:
    files: MANIFEST.yaml
    storage: s3h://minio1 <- Changed from store to storage here
  mutability: strict
  name: dataset-ex
  version: 1
```

2021-01-21 19:30 UTC, GustavoMaciel reviewed
Check if the comments I made also make sense for you

2021-01-21 19:30 UTC, GustavoMaciel commented on ml_git/file_system/local.py
> +            log.error('No storage for [%s]' % (manifest[STORAGE_KEY]), class_name=LOCAL_REPOSITORY_CLASS_NAME)
The same message was used below, maybe put it into the messages dictionary to be reused.
You can also look for other log usages in this PR, there's a bunch of hardcoded messages that could go to the dictionary.

2021-01-21 19:30 UTC, GustavoMaciel commented on ml_git/ml_git_message.py
> +    'DEBUG_STORE_AND_BUCKET': 'Store [%s] ; bucket [%s]',
Shouldn't this have storage instead of store?

2021-01-21 19:34 UTC, gilMars commented on ml_git/ml_git_message.py
> +    'DEBUG_STORE_AND_BUCKET': 'Store [%s] ; bucket [%s]',
Store or Storage?

2021-01-21 20:28 UTC, lucasncabral commented on ml_git/file_system/local.py
> +            log.error('No storage for [%s]' % (manifest[STORAGE_KEY]), class_name=LOCAL_REPOSITORY_CLASS_NAME)
This message and the others that were changed in this PR were moved to the centralized message file in 847ad30.

2021-01-21 20:28 UTC, lucasncabral commented on ml_git/ml_git_message.py
> +    'DEBUG_STORE_AND_BUCKET': 'Store [%s] ; bucket [%s]',
This message was updated on 847ad30.

2021-01-21 20:29 UTC, lucasncabral commented on ml_git/ml_git_message.py
> +    'DEBUG_STORE_AND_BUCKET': 'Store [%s] ; bucket [%s]',
Check previous comment.

2021-01-21 20:55 UTC, GustavoMaciel approved these changes

2021-01-22 00:23 UTC, andersonpablosilva requested changes
Please, take a look at the comments I've made.

2021-01-22 00:23 UTC, andersonpablosilva commented on ml_git/storages/multihash_storage.py
> +class MultihashStorage(object):
Update constant MULTI_HASH_STORAGE_NAME value.

2021-01-22 00:23 UTC, andersonpablosilva commented on ml_git/storages/s3_storage.py
> +class S3Storage(Storage):
Update constant S3STORAGE_NAME value.

2021-01-22 00:23 UTC, andersonpablosilva commented on ml_git/utils.py
> +from ml_git.constants import SPEC_EXTENSION, CONFIG_FILE, EntityType, ROOT_FILE_NAME, OLD_STORAGE_KEY, STORAGE_KEY
Maybe we can call it V1_STORAGE_KEY instead OLD_STORAGE_KEY. Same for OLD_MODELS_KEY and OLD_DATASETS_KEY.

2021-01-22 00:23 UTC, andersonpablosilva commented on ml_git/utils.py
>      if OLD_MODELS_KEY in hash:
Can we move OLD_MODELS_KEY and OLD_DATASETS_KEY definitions to constants.py?

2021-01-22 11:51 UTC, lucasncabral commented on ml_git/api.py
>          log.error('Aqui2')
This line was removed on 2f34d76.

2021-01-22 11:52 UTC, lucasncabral commented on ml_git/constants.py
> +STORAGE_FACTORY_CLASS_NAME = 'Store Factory'
The constant values ​​for the classes whose names have been changed were updated at 2f34d76.

2021-01-22 11:54 UTC, lucasncabral commented on ml_git/file_system/local.py
> +        log.info('Exporting tag [{}] from [{}] to [{}].'.format(tag, manifest[STORAGE_KEY], storage_dst_type),
Done 2f34d76.

2021-01-22 11:54 UTC, lucasncabral commented on ml_git/storages/azure_storage.py
> +class AzureMultihashStorage(Storage, MultihashStorage):
Done 2f34d76.

2021-01-22 11:54 UTC, lucasncabral commented on ml_git/storages/google_drive_storage.py
> +class GoogleDriveStorage(Storage):
Done 2f34d76.

2021-01-22 11:54 UTC, lucasncabral commented on ml_git/storages/multihash_storage.py
> +class MultihashStorage(object):
Done 2f34d76.

2021-01-22 11:54 UTC, lucasncabral commented on ml_git/storages/s3_storage.py
> +class S3Storage(Storage):
Done 2f34d76.

2021-01-22 12:54 UTC, lucasncabral commented on ml_git/utils.py
> +from ml_git.constants import SPEC_EXTENSION, CONFIG_FILE, EntityType, ROOT_FILE_NAME, OLD_STORAGE_KEY, STORAGE_KEY
The variables referring to the keys in version 1 of ml-git have been renamed.

2021-01-22 12:55 UTC, lucasncabral commented on ml_git/utils.py
>      if OLD_MODELS_KEY in hash:
Moved in 18d35e7.

2021-01-22 12:59 UTC, gilMars approved these changes

2021-01-22 18:24 UTC, andersonpablosilva approved these changes

2021-01-22 20:10 UTC, diego-pedroso commented on ml_git/utils.py
> +    have_old_dataset_path = os.path.exists(os.path.join(root_path, V1_DATASETS_KEY)) or os.path.exists(os.path.join(
This variable name sounds weird. Please rename to something like `old_dataset_path_exists`. Same is valid for `have_old_model_path`

2021-01-22 20:46 UTC, lucasncabral commented on ml_git/utils.py
> +    have_old_dataset_path = os.path.exists(os.path.join(root_path, V1_DATASETS_KEY)) or os.path.exists(os.path.join(
The variable names were updated in 9398193.

2021-01-22 21:28 UTC, diego-pedroso approved these changes

2021-01-22 22:08 UTC, merged