Updating status command to support data specialization plugins
HPInc/ml-git pull request #85
Opened 2021-02-05 20:16 UTC by gilMars

Output  example for tabular data with data specialization plugin:
```
Changes to be committed:                                                        
        New file: parquet2/insert_date=2020-07-23       ->      5995 ROWS

        Total rows to be commited: 5995.

Untracked files:
        README.md
        parquet/        ->      10 ROWS
        parquet2/insert_date=2020-07-25/   ->      6029 ROWS
        parquet2/insert_date=2020-07-24/   ->      6029 ROWS

Corrupted files:
```
Demonstration video:
https://asciinema.org/a/JA0u9T0LvJoH30uOo11xplvdJ

2021-02-08 11:43 UTC, lucasncabral commented on ml_git/repository.py
> +                print('\t%s%s\t->\t%d ROWS' % (files_status, base_path + '/', specialized_data[base_path]))
Is it possible to move this data type information to the plugin's return? Since for tabular data we will analyze the `ROWS`, but another type of data the plugin can analyze other information.

2021-02-08 11:43 UTC, lucasncabral commented on docs/plugins.md
> +Returns two dict that's contains the number of rows for each file.
Please add information about when this method is triggered.

2021-02-08 13:31 UTC, gilMars commented on ml_git/repository.py
> +        untracked_spec, new_files_spec = None, None
It was an ambiguity, the term 'spec', actually refers to specialization. The variable will be changed to untracked_specialized and new_files_specialized.

2021-02-08 14:58 UTC, gilMars commented on ml_git/repository.py
> +        print('\n\tTotal rows to be commited: %d.' % total)
Adjusted in 28eac40c.

2021-02-08 14:58 UTC, gilMars commented on ml_git/repository.py
> +
Adjusted in 28eac40c.

2021-02-08 14:58 UTC, gilMars commented on ml_git/repository.py
> +            plugin_insertion_data = plugin_caller.call(GET_ROWS_WORKSPACE_DATA, path, untracked_files, new_files)
Adjusted in 28eac40c.

2021-02-08 14:58 UTC, gilMars commented on ml_git/repository.py
> +        return PluginCaller(spec_content[self.__repo_type]['manifest'])
Adjusted in 28eac40c.

2021-02-08 14:58 UTC, gilMars commented on ml_git/repository.py
> +    def __load_plugin_caller(self, path, spec):
Adjusted in 28eac40c.

2021-02-08 14:58 UTC, gilMars commented on ml_git/repository.py
> +        untracked_spec, new_files_spec = None, None
Adjusted in 28eac40c.

2021-02-08 15:00 UTC, gilMars commented on ml_git/repository.py
> +                print('\t%s%s\t->\t%d ROWS' % (files_status, base_path + '/', specialized_data[base_path]))
For while the support is only to tabular data specialization.

2021-02-08 15:00 UTC, gilMars commented on docs/plugins.md
> +Returns two dict that's contains the number of rows for each file.
Adjusted in 28eac40c.

2021-02-08 20:14 UTC, GustavoMaciel approved these changes

2021-02-08 20:32 UTC, andersonpablosilva commented on ml_git/repository.py
> +                print('\t%s%s\t->\t%d ROWS' % (files_status, base_path + '/', specialized_data[base_path]))
According to the previous comments, I agree with @lucasncabral . We should move this to the plugin layer.

2021-02-09 12:07 UTC, gilMars commented on ml_git/repository.py
> +                print('\t%s%s\t->\t%d ROWS' % (files_status, base_path + '/', specialized_data[base_path]))
Adjusted in 5dfb7d00.

2021-02-09 12:12 UTC, gilMars commented on ml_git/ml_git_message.py
> +    'TOTAL_ROWS_TO_BE_COMMITED': '\n\tTotal rows to be commited: %d.',
Adjusted in 5dfb7d0.

2021-02-09 12:12 UTC, gilMars commented on docs/plugins.md
> +def get_rows_workspace_data(path, untracked_files, files_to_be_commited):
Adjusted in 5dfb7d0.

2021-02-09 12:12 UTC, gilMars commented on ml_git/constants.py
> +NUMBER_OF_ROWS = 'number_of_rows'
Removed in 5bb91956.

2021-02-09 12:13 UTC, gilMars commented on ml_git/repository.py
> +                self._print_files(new_files, full_option, 'New file: ')
Adjusted in 5bb91956.

2021-02-09 14:11 UTC, andersonpablosilva requested changes

2021-02-09 14:11 UTC, andersonpablosilva commented on docs/plugins.md
> +def get_rows_workspace_data(path, untracked_files, files_to_be_commited):
Once we have updated the method, we need to update the name to match its behavior. Also, the documentation is outdated.

2021-02-09 14:24 UTC, gilMars commented on docs/plugins.md
> +def get_rows_workspace_data(path, untracked_files, files_to_be_commited):
Updated in 528cafbf.

2021-02-09 14:41 UTC, Mun1z approved these changes

2021-02-09 17:29 UTC, lucasncabral approved these changes

2021-02-10 13:31 UTC, andersonpablosilva requested changes

2021-02-10 13:31 UTC, andersonpablosilva commented on docs/plugins.md
> +This signature will be triggered during the execution of the ml-git status command.
```suggestion
Responsible for generating status outputs for files in the user's workspace.
Returns two lists containing the formatted status output for untracked and added files and an a summarized output string for the total added.
This signature will be triggered during the execution of the ml-git status command.
```

2021-02-10 13:52 UTC, andersonpablosilva approved these changes

2021-02-12 21:22 UTC, diego-pedroso approved these changes

2021-02-19 14:26 UTC, merged