Adding models metrics command to show metrics
HPInc/ml-git pull request #93
Opened 2021-03-05 12:51 UTC by lucasncabral

This command aims to provide a way for the user to see the metrics of each tag of the entity.
The user is also allowed to define a path and file type (default is json) to export these metrics.

```
Usage: ml-git models metrics [OPTIONS] ML_ENTITY_NAME

  Shows metrics information for each tag of the entity.

Options:
  --export-path TEXT        Set the path to export metrics to a file. NOTE:
                            This option is required if --export-type is used.
  --export-type [csv|json]  Choose the format of the file that will be
                            generated with the metrics [default: json].
  --verbose                 Debug mode
```

**Example:** 
```
ml-git models metrics model-ex --export-path=C:\test\path --export-type=csv
```

**Output example:**

```
Tag: test__model-ex__1
+-----------------------------+---------------------+
|             Name            |        Value        |
+-----------------------------+---------------------+
|             Date            | 2021-03-02 08:30:16 |
| Related dataset - (version) |   dataset-ex - (1)  |
|  Related labels - (version) |    labels-ex - (1)  |
|           accuracy          |         10.0        |
|          precision          |         10.0        |
|            recall           |         10.0        |
+-----------------------------+---------------------+
Tag: test__model-ex__2
+-----------------------------+---------------------+
|             Name            |        Value        |
+-----------------------------+---------------------+
|             Date            | 2021-03-02 08:34:55 |
| Related dataset - (version) |   dataset-ex - (1)  |
|  Related labels - (version) |    labels-ex - (2)  |
|           accuracy          |         20.0        |
|          precision          |         20.0        |
|            recall           |         20.0        |
+-----------------------------+---------------------+

INFO - MLGit: The metrics were exported to the file: C:\test\path\model-ex-metrics.csv
```

**CSV file:**

```
Date,Tag,Related dataset - (version),Related labels - (version),accuracy,precision,recall
2021-03-03 10:12:51,test__model-ex__4,dataset-ex - (1),labels-ex - (1),10.0,10.0,10.0
2021-03-03 10:12:51,test__model-ex__4,dataset-ex - (1),labels-ex - (2),20.0,20.0,20.0
```

2021-03-08 19:08 UTC, gilMars commented on ml_git/commands/help_msg.py
> +EXPORT_METRICS_TYPE = 'Choose the format of the file that will be generated with the metrics [default: json].'
I guess that if change the the words 'format of the file...' to 'file format' would be interesting.

2021-03-09 11:58 UTC, lucasncabral commented on ml_git/commands/help_msg.py
> +EXPORT_METRICS_TYPE = 'Choose the format of the file that will be generated with the metrics [default: json].'
I think that this change can generate misunderstanding of the sentence, since it can be interpreted that the type of file will be generated and not the file itself.

2021-03-09 11:59 UTC, lucasncabral commented on ml_git/_metadata.py
> +            log.info(output_messages['INFO_METRICS_EXPORTED'].format(file_path))
Done 7e68142.

2021-03-09 12:35 UTC, gilMars commented on ml_git/commands/help_msg.py
> +EXPORT_METRICS_TYPE = 'Choose the format of the file that will be generated with the metrics [default: json].'
I agree.

2021-03-11 17:12 UTC, Mun1z approved these changes

2021-03-12 19:15 UTC, andersonpablosilva approved these changes

2021-03-12 19:21 UTC, gilMars approved these changes

2021-03-15 13:53 UTC, gpretto commented on tests/integration/test_38_models_metrics.py
> +        date_time = dt_object.strftime("%Y-%m-%d %H:%M:%S")
Can you change "dt_object to "date_object"? to keep consistency with "date_time".

2021-03-15 14:09 UTC, gpretto requested changes
Variable name change.

2021-03-15 14:33 UTC, lucasncabral commented on tests/integration/test_38_models_metrics.py
> +        date_time = dt_object.strftime("%Y-%m-%d %H:%M:%S")
I agree, to keep consistency the name of the variable was changed in 504d774.

2021-03-15 15:11 UTC, diego-pedroso approved these changes

2021-03-15 15:25 UTC, gpretto approved these changes

2021-03-15 15:41 UTC, diego-pedroso approved these changes

2021-03-18 14:48 UTC, merged